// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BankWithdrawArgs {
    pub npc_entity_id: u64,
    pub slot: u16,
    pub quantity: u32,
}

impl From<BankWithdrawArgs> for super::Reducer {
    fn from(args: BankWithdrawArgs) -> Self {
        Self::BankWithdraw {
            npc_entity_id: args.npc_entity_id,
            slot: args.slot,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for BankWithdrawArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `bank_withdraw`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait bank_withdraw {
    /// Request that the remote module invoke the reducer `bank_withdraw` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`bank_withdraw:bank_withdraw_then`] to run a callback after the reducer completes.
    fn bank_withdraw(&self, npc_entity_id: u64, slot: u16, quantity: u32) -> __sdk::Result<()> {
        self.bank_withdraw_then(npc_entity_id, slot, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `bank_withdraw` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn bank_withdraw_then(
        &self,
        npc_entity_id: u64,
        slot: u16,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl bank_withdraw for super::RemoteReducers {
    fn bank_withdraw_then(
        &self,
        npc_entity_id: u64,
        slot: u16,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BankWithdrawArgs {
                npc_entity_id,
                slot,
                quantity,
            },
            callback,
        )
    }
}
