// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChatLimit {
    pub identity: __sdk::Identity,
    pub window_start_us: i64,
    pub count: u32,
    pub last_shout_us: i64,
}

impl __sdk::InModule for ChatLimit {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChatLimit`.
///
/// Provides typed access to columns for query building.
pub struct ChatLimitCols {
    pub identity: __sdk::__query_builder::Col<ChatLimit, __sdk::Identity>,
    pub window_start_us: __sdk::__query_builder::Col<ChatLimit, i64>,
    pub count: __sdk::__query_builder::Col<ChatLimit, u32>,
    pub last_shout_us: __sdk::__query_builder::Col<ChatLimit, i64>,
}

impl __sdk::__query_builder::HasCols for ChatLimit {
    type Cols = ChatLimitCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChatLimitCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            window_start_us: __sdk::__query_builder::Col::new(table_name, "window_start_us"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
            last_shout_us: __sdk::__query_builder::Col::new(table_name, "last_shout_us"),
        }
    }
}

/// Indexed column accessor struct for the table `ChatLimit`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChatLimitIxCols {
    pub identity: __sdk::__query_builder::IxCol<ChatLimit, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ChatLimit {
    type IxCols = ChatLimitIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChatLimitIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChatLimit {}
