// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EquipItemArgs {
    pub page: u8,
    pub index: u16,
}

impl From<EquipItemArgs> for super::Reducer {
    fn from(args: EquipItemArgs) -> Self {
        Self::EquipItem {
            page: args.page,
            index: args.index,
        }
    }
}

impl __sdk::InModule for EquipItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `equip_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait equip_item {
    /// Request that the remote module invoke the reducer `equip_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`equip_item:equip_item_then`] to run a callback after the reducer completes.
    fn equip_item(&self, page: u8, index: u16) -> __sdk::Result<()> {
        self.equip_item_then(page, index, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `equip_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn equip_item_then(
        &self,
        page: u8,
        index: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl equip_item for super::RemoteReducers {
    fn equip_item_then(
        &self,
        page: u8,
        index: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EquipItemArgs { page, index }, callback)
    }
}
