// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::fallen_type::Fallen;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `fallen`.
///
/// Obtain a handle from the [`FallenTableAccess::fallen`] method on [`super::RemoteTables`],
/// like `ctx.db.fallen()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fallen().on_insert(...)`.
pub struct FallenTableHandle<'ctx> {
    imp: __sdk::TableHandle<Fallen>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `fallen`.
pub struct FallenTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for FallenTableAccessor {
    type Row = Fallen;
    type Handle<'db> = FallenTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.fallen()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fallen`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FallenTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FallenTableHandle`], which mediates access to the table `fallen`.
    fn fallen(&self) -> FallenTableHandle<'_>;
}

impl FallenTableAccess for super::RemoteTables {
    fn fallen(&self) -> FallenTableHandle<'_> {
        FallenTableHandle {
            imp: self.imp.get_table::<Fallen>("fallen"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FallenInsertCallbackId(__sdk::CallbackId);
pub struct FallenDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for FallenTableHandle<'ctx> {
    type Row = Fallen;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Fallen> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for FallenTableHandle<'ctx> {
    type Row = Fallen;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Fallen> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FallenInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FallenInsertCallbackId {
        FallenInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FallenInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FallenDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FallenDeleteCallbackId {
        FallenDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FallenDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for FallenTableHandle<'ctx> {
    type InsertCallbackId = FallenInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FallenInsertCallbackId {
        FallenInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FallenInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for FallenTableHandle<'ctx> {
    type DeleteCallbackId = FallenDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FallenDeleteCallbackId {
        FallenDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FallenDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FallenUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FallenTableHandle<'ctx> {
    type UpdateCallbackId = FallenUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FallenUpdateCallbackId {
        FallenUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FallenUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for FallenTableHandle<'ctx> {
    type UpdateCallbackId = FallenUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FallenUpdateCallbackId {
        FallenUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FallenUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `fallen`,
/// which allows point queries on the field of the same name
/// via the [`FallenEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fallen().entity_id().find(...)`.
pub struct FallenEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Fallen, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FallenTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `fallen`.
    pub fn entity_id(&self) -> FallenEntityIdUnique<'ctx> {
        FallenEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FallenEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Fallen> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Fallen>("fallen");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Fallen>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Fallen>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Fallen`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait fallenQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Fallen`.
    fn fallen(&self) -> __sdk::__query_builder::Table<Fallen>;
}

impl fallenQueryTableAccess for __sdk::QueryTableAccessor {
    fn fallen(&self) -> __sdk::__query_builder::Table<Fallen> {
        __sdk::__query_builder::Table::new("fallen")
    }
}
