// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FriendRequest {
    pub request_id: u64,
    pub to: __sdk::Identity,
    pub from: __sdk::Identity,
    pub from_name: String,
    pub expires_us: i64,
}

impl __sdk::InModule for FriendRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FriendRequest`.
///
/// Provides typed access to columns for query building.
pub struct FriendRequestCols {
    pub request_id: __sdk::__query_builder::Col<FriendRequest, u64>,
    pub to: __sdk::__query_builder::Col<FriendRequest, __sdk::Identity>,
    pub from: __sdk::__query_builder::Col<FriendRequest, __sdk::Identity>,
    pub from_name: __sdk::__query_builder::Col<FriendRequest, String>,
    pub expires_us: __sdk::__query_builder::Col<FriendRequest, i64>,
}

impl __sdk::__query_builder::HasCols for FriendRequest {
    type Cols = FriendRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FriendRequestCols {
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            to: __sdk::__query_builder::Col::new(table_name, "to"),
            from: __sdk::__query_builder::Col::new(table_name, "from"),
            from_name: __sdk::__query_builder::Col::new(table_name, "from_name"),
            expires_us: __sdk::__query_builder::Col::new(table_name, "expires_us"),
        }
    }
}

/// Indexed column accessor struct for the table `FriendRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct FriendRequestIxCols {
    pub request_id: __sdk::__query_builder::IxCol<FriendRequest, u64>,
    pub to: __sdk::__query_builder::IxCol<FriendRequest, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for FriendRequest {
    type IxCols = FriendRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FriendRequestIxCols {
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
            to: __sdk::__query_builder::IxCol::new(table_name, "to"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FriendRequest {}
