// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LevelUpSkillArgs {
    pub page: u8,
    pub index: u16,
}

impl From<LevelUpSkillArgs> for super::Reducer {
    fn from(args: LevelUpSkillArgs) -> Self {
        Self::LevelUpSkill {
            page: args.page,
            index: args.index,
        }
    }
}

impl __sdk::InModule for LevelUpSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `level_up_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait level_up_skill {
    /// Request that the remote module invoke the reducer `level_up_skill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`level_up_skill:level_up_skill_then`] to run a callback after the reducer completes.
    fn level_up_skill(&self, page: u8, index: u16) -> __sdk::Result<()> {
        self.level_up_skill_then(page, index, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `level_up_skill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn level_up_skill_then(
        &self,
        page: u8,
        index: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl level_up_skill for super::RemoteReducers {
    fn level_up_skill_then(
        &self,
        page: u8,
        index: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(LevelUpSkillArgs { page, index }, callback)
    }
}
