// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MonsterIdle {
    pub entity_id: u64,
    pub next_idle_us: i64,
}

impl __sdk::InModule for MonsterIdle {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MonsterIdle`.
///
/// Provides typed access to columns for query building.
pub struct MonsterIdleCols {
    pub entity_id: __sdk::__query_builder::Col<MonsterIdle, u64>,
    pub next_idle_us: __sdk::__query_builder::Col<MonsterIdle, i64>,
}

impl __sdk::__query_builder::HasCols for MonsterIdle {
    type Cols = MonsterIdleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MonsterIdleCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            next_idle_us: __sdk::__query_builder::Col::new(table_name, "next_idle_us"),
        }
    }
}

/// Indexed column accessor struct for the table `MonsterIdle`.
///
/// Provides typed access to indexed columns for query building.
pub struct MonsterIdleIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<MonsterIdle, u64>,
}

impl __sdk::__query_builder::HasIxCols for MonsterIdle {
    type IxCols = MonsterIdleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MonsterIdleIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MonsterIdle {}
