// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::motion_type::Motion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `motion`.
///
/// Obtain a handle from the [`MotionTableAccess::motion`] method on [`super::RemoteTables`],
/// like `ctx.db.motion()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.motion().on_insert(...)`.
pub struct MotionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Motion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `motion`.
pub struct MotionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MotionTableAccessor {
    type Row = Motion;
    type Handle<'db> = MotionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.motion()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `motion`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MotionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MotionTableHandle`], which mediates access to the table `motion`.
    fn motion(&self) -> MotionTableHandle<'_>;
}

impl MotionTableAccess for super::RemoteTables {
    fn motion(&self) -> MotionTableHandle<'_> {
        MotionTableHandle {
            imp: self.imp.get_table::<Motion>("motion"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MotionInsertCallbackId(__sdk::CallbackId);
pub struct MotionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MotionTableHandle<'ctx> {
    type Row = Motion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Motion> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MotionTableHandle<'ctx> {
    type Row = Motion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Motion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MotionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MotionInsertCallbackId {
        MotionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MotionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MotionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MotionDeleteCallbackId {
        MotionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MotionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MotionTableHandle<'ctx> {
    type InsertCallbackId = MotionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MotionInsertCallbackId {
        MotionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MotionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MotionTableHandle<'ctx> {
    type DeleteCallbackId = MotionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MotionDeleteCallbackId {
        MotionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MotionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MotionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MotionTableHandle<'ctx> {
    type UpdateCallbackId = MotionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MotionUpdateCallbackId {
        MotionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MotionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MotionTableHandle<'ctx> {
    type UpdateCallbackId = MotionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MotionUpdateCallbackId {
        MotionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MotionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `motion`,
/// which allows point queries on the field of the same name
/// via the [`MotionEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.motion().entity_id().find(...)`.
pub struct MotionEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Motion, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MotionTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `motion`.
    pub fn entity_id(&self) -> MotionEntityIdUnique<'ctx> {
        MotionEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MotionEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Motion> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Motion>("motion");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Motion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Motion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Motion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait motionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Motion`.
    fn motion(&self) -> __sdk::__query_builder::Table<Motion>;
}

impl motionQueryTableAccess for __sdk::QueryTableAccessor {
    fn motion(&self) -> __sdk::__query_builder::Table<Motion> {
        __sdk::__query_builder::Table::new("motion")
    }
}
