// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chat_channel_type::ChatChannel;
use super::chat_message_type::ChatMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_chat`.
///
/// Obtain a handle from the [`MyChatTableAccess::my_chat`] method on [`super::RemoteTables`],
/// like `ctx.db.my_chat()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_chat().on_insert(...)`.
pub struct MyChatTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChatMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_chat`.
pub struct MyChatTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyChatTableAccessor {
    type Row = ChatMessage;
    type Handle<'db> = MyChatTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_chat()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_chat`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyChatTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyChatTableHandle`], which mediates access to the table `my_chat`.
    fn my_chat(&self) -> MyChatTableHandle<'_>;
}

impl MyChatTableAccess for super::RemoteTables {
    fn my_chat(&self) -> MyChatTableHandle<'_> {
        MyChatTableHandle {
            imp: self.imp.get_table::<ChatMessage>("my_chat"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyChatInsertCallbackId(__sdk::CallbackId);
pub struct MyChatDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyChatTableHandle<'ctx> {
    type Row = ChatMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatMessage> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyChatTableHandle<'ctx> {
    type Row = ChatMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyChatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyChatInsertCallbackId {
        MyChatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyChatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyChatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyChatDeleteCallbackId {
        MyChatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyChatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyChatTableHandle<'ctx> {
    type InsertCallbackId = MyChatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyChatInsertCallbackId {
        MyChatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyChatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyChatTableHandle<'ctx> {
    type DeleteCallbackId = MyChatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyChatDeleteCallbackId {
        MyChatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyChatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChatMessage>("my_chat");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChatMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChatMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChatMessage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_chatQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChatMessage`.
    fn my_chat(&self) -> __sdk::__query_builder::Table<ChatMessage>;
}

impl my_chatQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_chat(&self) -> __sdk::__query_builder::Table<ChatMessage> {
        __sdk::__query_builder::Table::new("my_chat")
    }
}
