// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::friend_request_type::FriendRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_friend_requests`.
///
/// Obtain a handle from the [`MyFriendRequestsTableAccess::my_friend_requests`] method on [`super::RemoteTables`],
/// like `ctx.db.my_friend_requests()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_friend_requests().on_insert(...)`.
pub struct MyFriendRequestsTableHandle<'ctx> {
    imp: __sdk::TableHandle<FriendRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_friend_requests`.
pub struct MyFriendRequestsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyFriendRequestsTableAccessor {
    type Row = FriendRequest;
    type Handle<'db> = MyFriendRequestsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_friend_requests()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_friend_requests`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyFriendRequestsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyFriendRequestsTableHandle`], which mediates access to the table `my_friend_requests`.
    fn my_friend_requests(&self) -> MyFriendRequestsTableHandle<'_>;
}

impl MyFriendRequestsTableAccess for super::RemoteTables {
    fn my_friend_requests(&self) -> MyFriendRequestsTableHandle<'_> {
        MyFriendRequestsTableHandle {
            imp: self.imp.get_table::<FriendRequest>("my_friend_requests"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyFriendRequestsInsertCallbackId(__sdk::CallbackId);
pub struct MyFriendRequestsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyFriendRequestsTableHandle<'ctx> {
    type Row = FriendRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FriendRequest> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyFriendRequestsTableHandle<'ctx> {
    type Row = FriendRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FriendRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyFriendRequestsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFriendRequestsInsertCallbackId {
        MyFriendRequestsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyFriendRequestsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyFriendRequestsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFriendRequestsDeleteCallbackId {
        MyFriendRequestsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyFriendRequestsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyFriendRequestsTableHandle<'ctx> {
    type InsertCallbackId = MyFriendRequestsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFriendRequestsInsertCallbackId {
        MyFriendRequestsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyFriendRequestsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyFriendRequestsTableHandle<'ctx> {
    type DeleteCallbackId = MyFriendRequestsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFriendRequestsDeleteCallbackId {
        MyFriendRequestsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyFriendRequestsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FriendRequest>("my_friend_requests");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FriendRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FriendRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FriendRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_friend_requestsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FriendRequest`.
    fn my_friend_requests(&self) -> __sdk::__query_builder::Table<FriendRequest>;
}

impl my_friend_requestsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_friend_requests(&self) -> __sdk::__query_builder::Table<FriendRequest> {
        __sdk::__query_builder::Table::new("my_friend_requests")
    }
}
