// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcCastMotion {
    pub entity_id: u64,
    pub cast_motion: i32,
    pub action_motion: i32,
}

impl __sdk::InModule for NpcCastMotion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcCastMotion`.
///
/// Provides typed access to columns for query building.
pub struct NpcCastMotionCols {
    pub entity_id: __sdk::__query_builder::Col<NpcCastMotion, u64>,
    pub cast_motion: __sdk::__query_builder::Col<NpcCastMotion, i32>,
    pub action_motion: __sdk::__query_builder::Col<NpcCastMotion, i32>,
}

impl __sdk::__query_builder::HasCols for NpcCastMotion {
    type Cols = NpcCastMotionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcCastMotionCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            cast_motion: __sdk::__query_builder::Col::new(table_name, "cast_motion"),
            action_motion: __sdk::__query_builder::Col::new(table_name, "action_motion"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcCastMotion`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcCastMotionIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<NpcCastMotion, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcCastMotion {
    type IxCols = NpcCastMotionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcCastMotionIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcCastMotion {}
