// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PickupItemArgs {
    pub drop_id: u64,
}

impl From<PickupItemArgs> for super::Reducer {
    fn from(args: PickupItemArgs) -> Self {
        Self::PickupItem {
            drop_id: args.drop_id,
        }
    }
}

impl __sdk::InModule for PickupItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pickup_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pickup_item {
    /// Request that the remote module invoke the reducer `pickup_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pickup_item:pickup_item_then`] to run a callback after the reducer completes.
    fn pickup_item(&self, drop_id: u64) -> __sdk::Result<()> {
        self.pickup_item_then(drop_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `pickup_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pickup_item_then(
        &self,
        drop_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl pickup_item for super::RemoteReducers {
    fn pickup_item_then(
        &self,
        drop_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PickupItemArgs { drop_id }, callback)
    }
}
