// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct QuestTriggerArgs {
    pub name: String,
}

impl From<QuestTriggerArgs> for super::Reducer {
    fn from(args: QuestTriggerArgs) -> Self {
        Self::QuestTrigger { name: args.name }
    }
}

impl __sdk::InModule for QuestTriggerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `quest_trigger`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait quest_trigger {
    /// Request that the remote module invoke the reducer `quest_trigger` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`quest_trigger:quest_trigger_then`] to run a callback after the reducer completes.
    fn quest_trigger(&self, name: String) -> __sdk::Result<()> {
        self.quest_trigger_then(name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `quest_trigger` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn quest_trigger_then(
        &self,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl quest_trigger for super::RemoteReducers {
    fn quest_trigger_then(
        &self,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(QuestTriggerArgs { name }, callback)
    }
}
