// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::craft_slot_type::CraftSlot;
use super::craft_tool_type::CraftTool;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RefineItemArgs {
    pub tool: CraftTool,
    pub page: u8,
    pub index: u16,
    pub materials: Vec<CraftSlot>,
}

impl From<RefineItemArgs> for super::Reducer {
    fn from(args: RefineItemArgs) -> Self {
        Self::RefineItem {
            tool: args.tool,
            page: args.page,
            index: args.index,
            materials: args.materials,
        }
    }
}

impl __sdk::InModule for RefineItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `refine_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait refine_item {
    /// Request that the remote module invoke the reducer `refine_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`refine_item:refine_item_then`] to run a callback after the reducer completes.
    fn refine_item(
        &self,
        tool: CraftTool,
        page: u8,
        index: u16,
        materials: Vec<CraftSlot>,
    ) -> __sdk::Result<()> {
        self.refine_item_then(tool, page, index, materials, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `refine_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn refine_item_then(
        &self,
        tool: CraftTool,
        page: u8,
        index: u16,
        materials: Vec<CraftSlot>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl refine_item for super::RemoteReducers {
    fn refine_item_then(
        &self,
        tool: CraftTool,
        page: u8,
        index: u16,
        materials: Vec<CraftSlot>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RefineItemArgs {
                tool,
                page,
                index,
                materials,
            },
            callback,
        )
    }
}
