// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetHotbarSlotArgs {
    pub index: u8,
    pub kind: u8,
    pub page: u8,
    pub slot: u16,
}

impl From<SetHotbarSlotArgs> for super::Reducer {
    fn from(args: SetHotbarSlotArgs) -> Self {
        Self::SetHotbarSlot {
            index: args.index,
            kind: args.kind,
            page: args.page,
            slot: args.slot,
        }
    }
}

impl __sdk::InModule for SetHotbarSlotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_hotbar_slot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_hotbar_slot {
    /// Request that the remote module invoke the reducer `set_hotbar_slot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_hotbar_slot:set_hotbar_slot_then`] to run a callback after the reducer completes.
    fn set_hotbar_slot(&self, index: u8, kind: u8, page: u8, slot: u16) -> __sdk::Result<()> {
        self.set_hotbar_slot_then(index, kind, page, slot, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_hotbar_slot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_hotbar_slot_then(
        &self,
        index: u8,
        kind: u8,
        page: u8,
        slot: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_hotbar_slot for super::RemoteReducers {
    fn set_hotbar_slot_then(
        &self,
        index: u8,
        kind: u8,
        page: u8,
        slot: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetHotbarSlotArgs {
                index,
                kind,
                page,
                slot,
            },
            callback,
        )
    }
}
