// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetBasicStatArgs {
    pub name: String,
    pub stat: u8,
    pub value: i32,
}

impl From<SetBasicStatArgs> for super::Reducer {
    fn from(args: SetBasicStatArgs) -> Self {
        Self::SetBasicStat {
            name: args.name,
            stat: args.stat,
            value: args.value,
        }
    }
}

impl __sdk::InModule for SetBasicStatArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_basic_stat`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_basic_stat {
    /// Request that the remote module invoke the reducer `set_basic_stat` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_basic_stat:set_basic_stat_then`] to run a callback after the reducer completes.
    fn set_basic_stat(&self, name: String, stat: u8, value: i32) -> __sdk::Result<()> {
        self.set_basic_stat_then(name, stat, value, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_basic_stat` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_basic_stat_then(
        &self,
        name: String,
        stat: u8,
        value: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_basic_stat for super::RemoteReducers {
    fn set_basic_stat_then(
        &self,
        name: String,
        stat: u8,
        value: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetBasicStatArgs { name, stat, value }, callback)
    }
}
