// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::skill_cast_type::SkillCast;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `skill_cast`.
///
/// Obtain a handle from the [`SkillCastTableAccess::skill_cast`] method on [`super::RemoteTables`],
/// like `ctx.db.skill_cast()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_cast().on_insert(...)`.
pub struct SkillCastTableHandle<'ctx> {
    imp: __sdk::TableHandle<SkillCast>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `skill_cast`.
pub struct SkillCastTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SkillCastTableAccessor {
    type Row = SkillCast;
    type Handle<'db> = SkillCastTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.skill_cast()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `skill_cast`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SkillCastTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SkillCastTableHandle`], which mediates access to the table `skill_cast`.
    fn skill_cast(&self) -> SkillCastTableHandle<'_>;
}

impl SkillCastTableAccess for super::RemoteTables {
    fn skill_cast(&self) -> SkillCastTableHandle<'_> {
        SkillCastTableHandle {
            imp: self.imp.get_table::<SkillCast>("skill_cast"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SkillCastInsertCallbackId(__sdk::CallbackId);
pub struct SkillCastDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SkillCastTableHandle<'ctx> {
    type Row = SkillCast;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SkillCast> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SkillCastTableHandle<'ctx> {
    type Row = SkillCast;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SkillCast> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SkillCastInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillCastInsertCallbackId {
        SkillCastInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillCastInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SkillCastDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillCastDeleteCallbackId {
        SkillCastDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillCastDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SkillCastTableHandle<'ctx> {
    type InsertCallbackId = SkillCastInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillCastInsertCallbackId {
        SkillCastInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillCastInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SkillCastTableHandle<'ctx> {
    type DeleteCallbackId = SkillCastDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillCastDeleteCallbackId {
        SkillCastDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillCastDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SkillCastUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SkillCastTableHandle<'ctx> {
    type UpdateCallbackId = SkillCastUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillCastUpdateCallbackId {
        SkillCastUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillCastUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SkillCastTableHandle<'ctx> {
    type UpdateCallbackId = SkillCastUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillCastUpdateCallbackId {
        SkillCastUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillCastUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `skill_cast`,
/// which allows point queries on the field of the same name
/// via the [`SkillCastEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_cast().entity_id().find(...)`.
pub struct SkillCastEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SkillCast, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SkillCastTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `skill_cast`.
    pub fn entity_id(&self) -> SkillCastEntityIdUnique<'ctx> {
        SkillCastEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SkillCastEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SkillCast> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SkillCast>("skill_cast");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SkillCast>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SkillCast>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SkillCast`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait skill_castQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SkillCast`.
    fn skill_cast(&self) -> __sdk::__query_builder::Table<SkillCast>;
}

impl skill_castQueryTableAccess for __sdk::QueryTableAccessor {
    fn skill_cast(&self) -> __sdk::__query_builder::Table<SkillCast> {
        __sdk::__query_builder::Table::new("skill_cast")
    }
}
