// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::store_want_type::StoreWant;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `store_want`.
///
/// Obtain a handle from the [`StoreWantTableAccess::store_want`] method on [`super::RemoteTables`],
/// like `ctx.db.store_want()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.store_want().on_insert(...)`.
pub struct StoreWantTableHandle<'ctx> {
    imp: __sdk::TableHandle<StoreWant>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `store_want`.
pub struct StoreWantTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for StoreWantTableAccessor {
    type Row = StoreWant;
    type Handle<'db> = StoreWantTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.store_want()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `store_want`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StoreWantTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StoreWantTableHandle`], which mediates access to the table `store_want`.
    fn store_want(&self) -> StoreWantTableHandle<'_>;
}

impl StoreWantTableAccess for super::RemoteTables {
    fn store_want(&self) -> StoreWantTableHandle<'_> {
        StoreWantTableHandle {
            imp: self.imp.get_table::<StoreWant>("store_want"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StoreWantInsertCallbackId(__sdk::CallbackId);
pub struct StoreWantDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for StoreWantTableHandle<'ctx> {
    type Row = StoreWant;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StoreWant> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for StoreWantTableHandle<'ctx> {
    type Row = StoreWant;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StoreWant> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StoreWantInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StoreWantInsertCallbackId {
        StoreWantInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StoreWantInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StoreWantDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StoreWantDeleteCallbackId {
        StoreWantDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StoreWantDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for StoreWantTableHandle<'ctx> {
    type InsertCallbackId = StoreWantInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StoreWantInsertCallbackId {
        StoreWantInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StoreWantInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for StoreWantTableHandle<'ctx> {
    type DeleteCallbackId = StoreWantDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StoreWantDeleteCallbackId {
        StoreWantDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StoreWantDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StoreWantUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StoreWantTableHandle<'ctx> {
    type UpdateCallbackId = StoreWantUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StoreWantUpdateCallbackId {
        StoreWantUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StoreWantUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for StoreWantTableHandle<'ctx> {
    type UpdateCallbackId = StoreWantUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StoreWantUpdateCallbackId {
        StoreWantUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StoreWantUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `store_want`,
/// which allows point queries on the field of the same name
/// via the [`StoreWantIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.store_want().id().find(...)`.
pub struct StoreWantIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StoreWant, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StoreWantTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `store_want`.
    pub fn id(&self) -> StoreWantIdUnique<'ctx> {
        StoreWantIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StoreWantIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StoreWant> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StoreWant>("store_want");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StoreWant>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StoreWant>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StoreWant`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait store_wantQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StoreWant`.
    fn store_want(&self) -> __sdk::__query_builder::Table<StoreWant>;
}

impl store_wantQueryTableAccess for __sdk::QueryTableAccessor {
    fn store_want(&self) -> __sdk::__query_builder::Table<StoreWant> {
        __sdk::__query_builder::Table::new("store_want")
    }
}
