// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StoreWant {
    pub id: u64,
    pub store_entity: u64,
    pub item: String,
    pub quantity: u32,
    pub price: i64,
}

impl __sdk::InModule for StoreWant {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StoreWant`.
///
/// Provides typed access to columns for query building.
pub struct StoreWantCols {
    pub id: __sdk::__query_builder::Col<StoreWant, u64>,
    pub store_entity: __sdk::__query_builder::Col<StoreWant, u64>,
    pub item: __sdk::__query_builder::Col<StoreWant, String>,
    pub quantity: __sdk::__query_builder::Col<StoreWant, u32>,
    pub price: __sdk::__query_builder::Col<StoreWant, i64>,
}

impl __sdk::__query_builder::HasCols for StoreWant {
    type Cols = StoreWantCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StoreWantCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            store_entity: __sdk::__query_builder::Col::new(table_name, "store_entity"),
            item: __sdk::__query_builder::Col::new(table_name, "item"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            price: __sdk::__query_builder::Col::new(table_name, "price"),
        }
    }
}

/// Indexed column accessor struct for the table `StoreWant`.
///
/// Provides typed access to indexed columns for query building.
pub struct StoreWantIxCols {
    pub id: __sdk::__query_builder::IxCol<StoreWant, u64>,
    pub store_entity: __sdk::__query_builder::IxCol<StoreWant, u64>,
}

impl __sdk::__query_builder::HasIxCols for StoreWant {
    type IxCols = StoreWantIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StoreWantIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            store_entity: __sdk::__query_builder::IxCol::new(table_name, "store_entity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StoreWant {}
