// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TradeLockArgs {
    pub locked: bool,
}

impl From<TradeLockArgs> for super::Reducer {
    fn from(args: TradeLockArgs) -> Self {
        Self::TradeLock {
            locked: args.locked,
        }
    }
}

impl __sdk::InModule for TradeLockArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `trade_lock`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait trade_lock {
    /// Request that the remote module invoke the reducer `trade_lock` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`trade_lock:trade_lock_then`] to run a callback after the reducer completes.
    fn trade_lock(&self, locked: bool) -> __sdk::Result<()> {
        self.trade_lock_then(locked, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `trade_lock` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn trade_lock_then(
        &self,
        locked: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl trade_lock for super::RemoteReducers {
    fn trade_lock_then(
        &self,
        locked: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TradeLockArgs { locked }, callback)
    }
}
