// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::trade_request_type::TradeRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `trade_request`.
///
/// Obtain a handle from the [`TradeRequestTableAccess::trade_request`] method on [`super::RemoteTables`],
/// like `ctx.db.trade_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.trade_request().on_insert(...)`.
pub struct TradeRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<TradeRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `trade_request`.
pub struct TradeRequestTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TradeRequestTableAccessor {
    type Row = TradeRequest;
    type Handle<'db> = TradeRequestTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.trade_request()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `trade_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TradeRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TradeRequestTableHandle`], which mediates access to the table `trade_request`.
    fn trade_request(&self) -> TradeRequestTableHandle<'_>;
}

impl TradeRequestTableAccess for super::RemoteTables {
    fn trade_request(&self) -> TradeRequestTableHandle<'_> {
        TradeRequestTableHandle {
            imp: self.imp.get_table::<TradeRequest>("trade_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TradeRequestInsertCallbackId(__sdk::CallbackId);
pub struct TradeRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TradeRequestTableHandle<'ctx> {
    type Row = TradeRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TradeRequest> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TradeRequestTableHandle<'ctx> {
    type Row = TradeRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TradeRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TradeRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TradeRequestInsertCallbackId {
        TradeRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TradeRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TradeRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TradeRequestDeleteCallbackId {
        TradeRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TradeRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TradeRequestTableHandle<'ctx> {
    type InsertCallbackId = TradeRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TradeRequestInsertCallbackId {
        TradeRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TradeRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TradeRequestTableHandle<'ctx> {
    type DeleteCallbackId = TradeRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TradeRequestDeleteCallbackId {
        TradeRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TradeRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TradeRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TradeRequestTableHandle<'ctx> {
    type UpdateCallbackId = TradeRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TradeRequestUpdateCallbackId {
        TradeRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TradeRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for TradeRequestTableHandle<'ctx> {
    type UpdateCallbackId = TradeRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TradeRequestUpdateCallbackId {
        TradeRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TradeRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `request_id` unique index on the table `trade_request`,
/// which allows point queries on the field of the same name
/// via the [`TradeRequestRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.trade_request().request_id().find(...)`.
pub struct TradeRequestRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TradeRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TradeRequestTableHandle<'ctx> {
    /// Get a handle on the `request_id` unique index on the table `trade_request`.
    pub fn request_id(&self) -> TradeRequestRequestIdUnique<'ctx> {
        TradeRequestRequestIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("request_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TradeRequestRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `request_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TradeRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TradeRequest>("trade_request");
    _table.add_unique_constraint::<u64>("request_id", |row| &row.request_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TradeRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TradeRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TradeRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait trade_requestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TradeRequest`.
    fn trade_request(&self) -> __sdk::__query_builder::Table<TradeRequest>;
}

impl trade_requestQueryTableAccess for __sdk::QueryTableAccessor {
    fn trade_request(&self) -> __sdk::__query_builder::Table<TradeRequest> {
        __sdk::__query_builder::Table::new("trade_request")
    }
}
