// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TradeRequest {
    pub request_id: u64,
    pub from: __sdk::Identity,
    pub to: __sdk::Identity,
    pub expires_us: i64,
}

impl __sdk::InModule for TradeRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TradeRequest`.
///
/// Provides typed access to columns for query building.
pub struct TradeRequestCols {
    pub request_id: __sdk::__query_builder::Col<TradeRequest, u64>,
    pub from: __sdk::__query_builder::Col<TradeRequest, __sdk::Identity>,
    pub to: __sdk::__query_builder::Col<TradeRequest, __sdk::Identity>,
    pub expires_us: __sdk::__query_builder::Col<TradeRequest, i64>,
}

impl __sdk::__query_builder::HasCols for TradeRequest {
    type Cols = TradeRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TradeRequestCols {
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            from: __sdk::__query_builder::Col::new(table_name, "from"),
            to: __sdk::__query_builder::Col::new(table_name, "to"),
            expires_us: __sdk::__query_builder::Col::new(table_name, "expires_us"),
        }
    }
}

/// Indexed column accessor struct for the table `TradeRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct TradeRequestIxCols {
    pub request_id: __sdk::__query_builder::IxCol<TradeRequest, u64>,
    pub to: __sdk::__query_builder::IxCol<TradeRequest, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for TradeRequest {
    type IxCols = TradeRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TradeRequestIxCols {
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
            to: __sdk::__query_builder::IxCol::new(table_name, "to"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TradeRequest {}
