// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnequipItemArgs {
    pub equipment_slot: u8,
}

impl From<UnequipItemArgs> for super::Reducer {
    fn from(args: UnequipItemArgs) -> Self {
        Self::UnequipItem {
            equipment_slot: args.equipment_slot,
        }
    }
}

impl __sdk::InModule for UnequipItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unequip_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unequip_item {
    /// Request that the remote module invoke the reducer `unequip_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`unequip_item:unequip_item_then`] to run a callback after the reducer completes.
    fn unequip_item(&self, equipment_slot: u8) -> __sdk::Result<()> {
        self.unequip_item_then(equipment_slot, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `unequip_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unequip_item_then(
        &self,
        equipment_slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl unequip_item for super::RemoteReducers {
    fn unequip_item_then(
        &self,
        equipment_slot: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UnequipItemArgs { equipment_slot }, callback)
    }
}
