// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_rates_type::WorldRates;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_rates`.
///
/// Obtain a handle from the [`WorldRatesTableAccess::world_rates`] method on [`super::RemoteTables`],
/// like `ctx.db.world_rates()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_rates().on_insert(...)`.
pub struct WorldRatesTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldRates>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `world_rates`.
pub struct WorldRatesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for WorldRatesTableAccessor {
    type Row = WorldRates;
    type Handle<'db> = WorldRatesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.world_rates()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_rates`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldRatesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldRatesTableHandle`], which mediates access to the table `world_rates`.
    fn world_rates(&self) -> WorldRatesTableHandle<'_>;
}

impl WorldRatesTableAccess for super::RemoteTables {
    fn world_rates(&self) -> WorldRatesTableHandle<'_> {
        WorldRatesTableHandle {
            imp: self.imp.get_table::<WorldRates>("world_rates"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldRatesInsertCallbackId(__sdk::CallbackId);
pub struct WorldRatesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for WorldRatesTableHandle<'ctx> {
    type Row = WorldRates;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldRates> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for WorldRatesTableHandle<'ctx> {
    type Row = WorldRates;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldRates> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldRatesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldRatesInsertCallbackId {
        WorldRatesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldRatesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldRatesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldRatesDeleteCallbackId {
        WorldRatesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldRatesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for WorldRatesTableHandle<'ctx> {
    type InsertCallbackId = WorldRatesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldRatesInsertCallbackId {
        WorldRatesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldRatesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for WorldRatesTableHandle<'ctx> {
    type DeleteCallbackId = WorldRatesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldRatesDeleteCallbackId {
        WorldRatesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldRatesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldRatesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldRatesTableHandle<'ctx> {
    type UpdateCallbackId = WorldRatesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldRatesUpdateCallbackId {
        WorldRatesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldRatesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for WorldRatesTableHandle<'ctx> {
    type UpdateCallbackId = WorldRatesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldRatesUpdateCallbackId {
        WorldRatesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldRatesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_rates`,
/// which allows point queries on the field of the same name
/// via the [`WorldRatesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_rates().id().find(...)`.
pub struct WorldRatesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldRates, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldRatesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_rates`.
    pub fn id(&self) -> WorldRatesIdUnique<'ctx> {
        WorldRatesIdUnique {
            imp: self.imp.get_unique_constraint::<u8>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldRatesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<WorldRates> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldRates>("world_rates");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldRates>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldRates>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldRates`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_ratesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldRates`.
    fn world_rates(&self) -> __sdk::__query_builder::Table<WorldRates>;
}

impl world_ratesQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_rates(&self) -> __sdk::__query_builder::Table<WorldRates> {
        __sdk::__query_builder::Table::new("world_rates")
    }
}
