// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct XpEvent {
    pub identity: __sdk::Identity,
    pub xp: u64,
    pub level: u32,
}

impl __sdk::InModule for XpEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `XpEvent`.
///
/// Provides typed access to columns for query building.
pub struct XpEventCols {
    pub identity: __sdk::__query_builder::Col<XpEvent, __sdk::Identity>,
    pub xp: __sdk::__query_builder::Col<XpEvent, u64>,
    pub level: __sdk::__query_builder::Col<XpEvent, u32>,
}

impl __sdk::__query_builder::HasCols for XpEvent {
    type Cols = XpEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        XpEventCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            xp: __sdk::__query_builder::Col::new(table_name, "xp"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
        }
    }
}

/// Indexed column accessor struct for the table `XpEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct XpEventIxCols {}

impl __sdk::__query_builder::HasIxCols for XpEvent {
    type IxCols = XpEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        XpEventIxCols {}
    }
}
