// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::xp_event_type::XpEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `xp_event`.
///
/// Obtain a handle from the [`XpEventTableAccess::xp_event`] method on [`super::RemoteTables`],
/// like `ctx.db.xp_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.xp_event().on_insert(...)`.
pub struct XpEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<XpEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `xp_event`.
pub struct XpEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for XpEventTableAccessor {
    type Row = XpEvent;
    type Handle<'db> = XpEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.xp_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `xp_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait XpEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`XpEventTableHandle`], which mediates access to the table `xp_event`.
    fn xp_event(&self) -> XpEventTableHandle<'_>;
}

impl XpEventTableAccess for super::RemoteTables {
    fn xp_event(&self) -> XpEventTableHandle<'_> {
        XpEventTableHandle {
            imp: self.imp.get_table::<XpEvent>("xp_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct XpEventInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for XpEventTableHandle<'ctx> {
    type Row = XpEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = XpEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::EventTable for XpEventTableHandle<'ctx> {
    type Row = XpEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = XpEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = XpEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> XpEventInsertCallbackId {
        XpEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: XpEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for XpEventTableHandle<'ctx> {
    type InsertCallbackId = XpEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> XpEventInsertCallbackId {
        XpEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: XpEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<XpEvent>("xp_event");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<XpEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<XpEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `XpEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait xp_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `XpEvent`.
    fn xp_event(&self) -> __sdk::__query_builder::Table<XpEvent>;
}

impl xp_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn xp_event(&self) -> __sdk::__query_builder::Table<XpEvent> {
        __sdk::__query_builder::Table::new("xp_event")
    }
}
