// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::zone_info_type::ZoneInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `zone_info`.
///
/// Obtain a handle from the [`ZoneInfoTableAccess::zone_info`] method on [`super::RemoteTables`],
/// like `ctx.db.zone_info()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.zone_info().on_insert(...)`.
pub struct ZoneInfoTableHandle<'ctx> {
    imp: __sdk::TableHandle<ZoneInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `zone_info`.
pub struct ZoneInfoTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ZoneInfoTableAccessor {
    type Row = ZoneInfo;
    type Handle<'db> = ZoneInfoTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.zone_info()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `zone_info`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ZoneInfoTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ZoneInfoTableHandle`], which mediates access to the table `zone_info`.
    fn zone_info(&self) -> ZoneInfoTableHandle<'_>;
}

impl ZoneInfoTableAccess for super::RemoteTables {
    fn zone_info(&self) -> ZoneInfoTableHandle<'_> {
        ZoneInfoTableHandle {
            imp: self.imp.get_table::<ZoneInfo>("zone_info"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ZoneInfoInsertCallbackId(__sdk::CallbackId);
pub struct ZoneInfoDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ZoneInfoTableHandle<'ctx> {
    type Row = ZoneInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ZoneInfo> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ZoneInfoTableHandle<'ctx> {
    type Row = ZoneInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ZoneInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ZoneInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZoneInfoInsertCallbackId {
        ZoneInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ZoneInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ZoneInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZoneInfoDeleteCallbackId {
        ZoneInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ZoneInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ZoneInfoTableHandle<'ctx> {
    type InsertCallbackId = ZoneInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZoneInfoInsertCallbackId {
        ZoneInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ZoneInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ZoneInfoTableHandle<'ctx> {
    type DeleteCallbackId = ZoneInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZoneInfoDeleteCallbackId {
        ZoneInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ZoneInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ZoneInfoUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ZoneInfoTableHandle<'ctx> {
    type UpdateCallbackId = ZoneInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ZoneInfoUpdateCallbackId {
        ZoneInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ZoneInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ZoneInfoTableHandle<'ctx> {
    type UpdateCallbackId = ZoneInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ZoneInfoUpdateCallbackId {
        ZoneInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ZoneInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `zone_id` unique index on the table `zone_info`,
/// which allows point queries on the field of the same name
/// via the [`ZoneInfoZoneIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.zone_info().zone_id().find(...)`.
pub struct ZoneInfoZoneIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ZoneInfo, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ZoneInfoTableHandle<'ctx> {
    /// Get a handle on the `zone_id` unique index on the table `zone_info`.
    pub fn zone_id(&self) -> ZoneInfoZoneIdUnique<'ctx> {
        ZoneInfoZoneIdUnique {
            imp: self.imp.get_unique_constraint::<u16>("zone_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ZoneInfoZoneIdUnique<'ctx> {
    /// Find the subscribed row whose `zone_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<ZoneInfo> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ZoneInfo>("zone_info");
    _table.add_unique_constraint::<u16>("zone_id", |row| &row.zone_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ZoneInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ZoneInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ZoneInfo`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait zone_infoQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ZoneInfo`.
    fn zone_info(&self) -> __sdk::__query_builder::Table<ZoneInfo>;
}

impl zone_infoQueryTableAccess for __sdk::QueryTableAccessor {
    fn zone_info(&self) -> __sdk::__query_builder::Table<ZoneInfo> {
        __sdk::__query_builder::Table::new("zone_info")
    }
}
