// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ZoneInfo {
    pub zone_id: u16,
    pub name: String,
    pub start_x: f32,
    pub start_y: f32,
    pub revive_x: f32,
    pub revive_y: f32,
    pub min_x: f32,
    pub min_y: f32,
    pub max_x: f32,
    pub max_y: f32,
}

impl __sdk::InModule for ZoneInfo {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ZoneInfo`.
///
/// Provides typed access to columns for query building.
pub struct ZoneInfoCols {
    pub zone_id: __sdk::__query_builder::Col<ZoneInfo, u16>,
    pub name: __sdk::__query_builder::Col<ZoneInfo, String>,
    pub start_x: __sdk::__query_builder::Col<ZoneInfo, f32>,
    pub start_y: __sdk::__query_builder::Col<ZoneInfo, f32>,
    pub revive_x: __sdk::__query_builder::Col<ZoneInfo, f32>,
    pub revive_y: __sdk::__query_builder::Col<ZoneInfo, f32>,
    pub min_x: __sdk::__query_builder::Col<ZoneInfo, f32>,
    pub min_y: __sdk::__query_builder::Col<ZoneInfo, f32>,
    pub max_x: __sdk::__query_builder::Col<ZoneInfo, f32>,
    pub max_y: __sdk::__query_builder::Col<ZoneInfo, f32>,
}

impl __sdk::__query_builder::HasCols for ZoneInfo {
    type Cols = ZoneInfoCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ZoneInfoCols {
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            start_x: __sdk::__query_builder::Col::new(table_name, "start_x"),
            start_y: __sdk::__query_builder::Col::new(table_name, "start_y"),
            revive_x: __sdk::__query_builder::Col::new(table_name, "revive_x"),
            revive_y: __sdk::__query_builder::Col::new(table_name, "revive_y"),
            min_x: __sdk::__query_builder::Col::new(table_name, "min_x"),
            min_y: __sdk::__query_builder::Col::new(table_name, "min_y"),
            max_x: __sdk::__query_builder::Col::new(table_name, "max_x"),
            max_y: __sdk::__query_builder::Col::new(table_name, "max_y"),
        }
    }
}

/// Indexed column accessor struct for the table `ZoneInfo`.
///
/// Provides typed access to indexed columns for query building.
pub struct ZoneInfoIxCols {
    pub zone_id: __sdk::__query_builder::IxCol<ZoneInfo, u16>,
}

impl __sdk::__query_builder::HasIxCols for ZoneInfo {
    type IxCols = ZoneInfoIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ZoneInfoIxCols {
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ZoneInfo {}
