[package]
name = "rose-stdb-import"
version = "0.1.0"
edition = "2021"
default-run = "rose-stdb-import"


[dependencies]
rose-data = { path = "../crates/rose-data" }
rose-data-irose = { path = "../crates/rose-data-irose" }
rose-file-readers = { path = "../crates/rose-file-readers" }
serde_json = "1"
rose-game-data = { path = "../crates/rose-game-data" }
rose-game-overrides = { path = "../crates/rose-game-overrides" }
base64 = "0.22"
anyhow = "1"
