[package]
name = "rose-stdb-import"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
rose-data = { path = "../../rose-offline/rose-data" }
rose-data-irose = { path = "../../rose-offline/rose-data-irose" }
rose-file-readers = { path = "../../rose-offline/rose-file-readers" }
serde_json = "1"
