// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AbandonQuestArgs {
    pub slot: u8,
    pub quest_id: u32,
}

impl From<AbandonQuestArgs> for super::Reducer {
    fn from(args: AbandonQuestArgs) -> Self {
        Self::AbandonQuest {
            slot: args.slot,
            quest_id: args.quest_id,
        }
    }
}

impl __sdk::InModule for AbandonQuestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `abandon_quest`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait abandon_quest {
    /// Request that the remote module invoke the reducer `abandon_quest` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`abandon_quest:abandon_quest_then`] to run a callback after the reducer completes.
    fn abandon_quest(&self, slot: u8, quest_id: u32) -> __sdk::Result<()> {
        self.abandon_quest_then(slot, quest_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `abandon_quest` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn abandon_quest_then(
        &self,
        slot: u8,
        quest_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl abandon_quest for super::RemoteReducers {
    fn abandon_quest_then(
        &self,
        slot: u8,
        quest_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AbandonQuestArgs { slot, quest_id }, callback)
    }
}
