// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminGiveQuestArgs {
    pub player_name: String,
    pub quest_id: u32,
    pub item_number: u32,
    pub quantity: u32,
}

impl From<AdminGiveQuestArgs> for super::Reducer {
    fn from(args: AdminGiveQuestArgs) -> Self {
        Self::AdminGiveQuest {
            player_name: args.player_name,
            quest_id: args.quest_id,
            item_number: args.item_number,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for AdminGiveQuestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_give_quest`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_give_quest {
    /// Request that the remote module invoke the reducer `admin_give_quest` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_give_quest:admin_give_quest_then`] to run a callback after the reducer completes.
    fn admin_give_quest(
        &self,
        player_name: String,
        quest_id: u32,
        item_number: u32,
        quantity: u32,
    ) -> __sdk::Result<()> {
        self.admin_give_quest_then(player_name, quest_id, item_number, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_give_quest` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_give_quest_then(
        &self,
        player_name: String,
        quest_id: u32,
        item_number: u32,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_give_quest for super::RemoteReducers {
    fn admin_give_quest_then(
        &self,
        player_name: String,
        quest_id: u32,
        item_number: u32,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminGiveQuestArgs {
                player_name,
                quest_id,
                item_number,
                quantity,
            },
            callback,
        )
    }
}
