// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminSetItemLifeArgs {
    pub player_name: String,
    pub kind: u8,
    pub slot: u8,
    pub index: u16,
    pub life: u16,
}

impl From<AdminSetItemLifeArgs> for super::Reducer {
    fn from(args: AdminSetItemLifeArgs) -> Self {
        Self::AdminSetItemLife {
            player_name: args.player_name,
            kind: args.kind,
            slot: args.slot,
            index: args.index,
            life: args.life,
        }
    }
}

impl __sdk::InModule for AdminSetItemLifeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_set_item_life`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_set_item_life {
    /// Request that the remote module invoke the reducer `admin_set_item_life` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_set_item_life:admin_set_item_life_then`] to run a callback after the reducer completes.
    fn admin_set_item_life(
        &self,
        player_name: String,
        kind: u8,
        slot: u8,
        index: u16,
        life: u16,
    ) -> __sdk::Result<()> {
        self.admin_set_item_life_then(player_name, kind, slot, index, life, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_set_item_life` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_set_item_life_then(
        &self,
        player_name: String,
        kind: u8,
        slot: u8,
        index: u16,
        life: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_set_item_life for super::RemoteReducers {
    fn admin_set_item_life_then(
        &self,
        player_name: String,
        kind: u8,
        slot: u8,
        index: u16,
        life: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminSetItemLifeArgs {
                player_name,
                kind,
                slot,
                index,
                life,
            },
            callback,
        )
    }
}
