// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CastSkillArgs {
    pub page: u8,
    pub index: u16,
    pub target: Option<u64>,
    pub x: f32,
    pub y: f32,
}

impl From<CastSkillArgs> for super::Reducer {
    fn from(args: CastSkillArgs) -> Self {
        Self::CastSkill {
            page: args.page,
            index: args.index,
            target: args.target,
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for CastSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cast_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cast_skill {
    /// Request that the remote module invoke the reducer `cast_skill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cast_skill:cast_skill_then`] to run a callback after the reducer completes.
    fn cast_skill(
        &self,
        page: u8,
        index: u16,
        target: Option<u64>,
        x: f32,
        y: f32,
    ) -> __sdk::Result<()> {
        self.cast_skill_then(page, index, target, x, y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cast_skill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cast_skill_then(
        &self,
        page: u8,
        index: u16,
        target: Option<u64>,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cast_skill for super::RemoteReducers {
    fn cast_skill_then(
        &self,
        page: u8,
        index: u16,
        target: Option<u64>,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CastSkillArgs {
                page,
                index,
                target,
                x,
                y,
            },
            callback,
        )
    }
}
