// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::chat_channel_type::ChatChannel;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChatMessage {
    pub id: u64,
    pub recipient: __sdk::Identity,
    pub channel: ChatChannel,
    pub from_name: String,
    pub from_entity: Option<u64>,
    pub to_name: String,
    pub text: String,
    pub at_us: i64,
}

impl __sdk::InModule for ChatMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChatMessage`.
///
/// Provides typed access to columns for query building.
pub struct ChatMessageCols {
    pub id: __sdk::__query_builder::Col<ChatMessage, u64>,
    pub recipient: __sdk::__query_builder::Col<ChatMessage, __sdk::Identity>,
    pub channel: __sdk::__query_builder::Col<ChatMessage, ChatChannel>,
    pub from_name: __sdk::__query_builder::Col<ChatMessage, String>,
    pub from_entity: __sdk::__query_builder::Col<ChatMessage, Option<u64>>,
    pub to_name: __sdk::__query_builder::Col<ChatMessage, String>,
    pub text: __sdk::__query_builder::Col<ChatMessage, String>,
    pub at_us: __sdk::__query_builder::Col<ChatMessage, i64>,
}

impl __sdk::__query_builder::HasCols for ChatMessage {
    type Cols = ChatMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChatMessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            recipient: __sdk::__query_builder::Col::new(table_name, "recipient"),
            channel: __sdk::__query_builder::Col::new(table_name, "channel"),
            from_name: __sdk::__query_builder::Col::new(table_name, "from_name"),
            from_entity: __sdk::__query_builder::Col::new(table_name, "from_entity"),
            to_name: __sdk::__query_builder::Col::new(table_name, "to_name"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            at_us: __sdk::__query_builder::Col::new(table_name, "at_us"),
        }
    }
}

/// Indexed column accessor struct for the table `ChatMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChatMessageIxCols {
    pub id: __sdk::__query_builder::IxCol<ChatMessage, u64>,
    pub recipient: __sdk::__query_builder::IxCol<ChatMessage, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ChatMessage {
    type IxCols = ChatMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChatMessageIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            recipient: __sdk::__query_builder::IxCol::new(table_name, "recipient"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChatMessage {}
