// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCharacterArgs {
    pub name: String,
    pub gender: u8,
    pub face: u8,
    pub hair: u8,
}

impl From<CreateCharacterArgs> for super::Reducer {
    fn from(args: CreateCharacterArgs) -> Self {
        Self::CreateCharacter {
            name: args.name,
            gender: args.gender,
            face: args.face,
            hair: args.hair,
        }
    }
}

impl __sdk::InModule for CreateCharacterArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_character {
    /// Request that the remote module invoke the reducer `create_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_character:create_character_then`] to run a callback after the reducer completes.
    fn create_character(&self, name: String, gender: u8, face: u8, hair: u8) -> __sdk::Result<()> {
        self.create_character_then(name, gender, face, hair, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_character` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_character_then(
        &self,
        name: String,
        gender: u8,
        face: u8,
        hair: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_character for super::RemoteReducers {
    fn create_character_then(
        &self,
        name: String,
        gender: u8,
        face: u8,
        hair: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateCharacterArgs {
                name,
                gender,
                face,
                hair,
            },
            callback,
        )
    }
}
