// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DamageEvent {
    pub attacker: u64,
    pub defender: u64,
    pub amount: i32,
    pub is_critical: bool,
    pub killed: bool,
    pub attacker_moving: bool,
    pub at_us: i64,
}

impl __sdk::InModule for DamageEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DamageEvent`.
///
/// Provides typed access to columns for query building.
pub struct DamageEventCols {
    pub attacker: __sdk::__query_builder::Col<DamageEvent, u64>,
    pub defender: __sdk::__query_builder::Col<DamageEvent, u64>,
    pub amount: __sdk::__query_builder::Col<DamageEvent, i32>,
    pub is_critical: __sdk::__query_builder::Col<DamageEvent, bool>,
    pub killed: __sdk::__query_builder::Col<DamageEvent, bool>,
    pub attacker_moving: __sdk::__query_builder::Col<DamageEvent, bool>,
    pub at_us: __sdk::__query_builder::Col<DamageEvent, i64>,
}

impl __sdk::__query_builder::HasCols for DamageEvent {
    type Cols = DamageEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DamageEventCols {
            attacker: __sdk::__query_builder::Col::new(table_name, "attacker"),
            defender: __sdk::__query_builder::Col::new(table_name, "defender"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
            is_critical: __sdk::__query_builder::Col::new(table_name, "is_critical"),
            killed: __sdk::__query_builder::Col::new(table_name, "killed"),
            attacker_moving: __sdk::__query_builder::Col::new(table_name, "attacker_moving"),
            at_us: __sdk::__query_builder::Col::new(table_name, "at_us"),
        }
    }
}

/// Indexed column accessor struct for the table `DamageEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct DamageEventIxCols {}

impl __sdk::__query_builder::HasIxCols for DamageEvent {
    type IxCols = DamageEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DamageEventIxCols {}
    }
}
