// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::damage_event_type::DamageEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `damage_event`.
///
/// Obtain a handle from the [`DamageEventTableAccess::damage_event`] method on [`super::RemoteTables`],
/// like `ctx.db.damage_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.damage_event().on_insert(...)`.
pub struct DamageEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<DamageEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `damage_event`.
pub struct DamageEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for DamageEventTableAccessor {
    type Row = DamageEvent;
    type Handle<'db> = DamageEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.damage_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `damage_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DamageEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DamageEventTableHandle`], which mediates access to the table `damage_event`.
    fn damage_event(&self) -> DamageEventTableHandle<'_>;
}

impl DamageEventTableAccess for super::RemoteTables {
    fn damage_event(&self) -> DamageEventTableHandle<'_> {
        DamageEventTableHandle {
            imp: self.imp.get_table::<DamageEvent>("damage_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DamageEventInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for DamageEventTableHandle<'ctx> {
    type Row = DamageEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DamageEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::EventTable for DamageEventTableHandle<'ctx> {
    type Row = DamageEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DamageEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DamageEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DamageEventInsertCallbackId {
        DamageEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DamageEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for DamageEventTableHandle<'ctx> {
    type InsertCallbackId = DamageEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DamageEventInsertCallbackId {
        DamageEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DamageEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DamageEvent>("damage_event");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DamageEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DamageEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DamageEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait damage_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DamageEvent`.
    fn damage_event(&self) -> __sdk::__query_builder::Table<DamageEvent>;
}

impl damage_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn damage_event(&self) -> __sdk::__query_builder::Table<DamageEvent> {
        __sdk::__query_builder::Table::new("damage_event")
    }
}
