// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::driving_type::Driving;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `driving`.
///
/// Obtain a handle from the [`DrivingTableAccess::driving`] method on [`super::RemoteTables`],
/// like `ctx.db.driving()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.driving().on_insert(...)`.
pub struct DrivingTableHandle<'ctx> {
    imp: __sdk::TableHandle<Driving>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `driving`.
pub struct DrivingTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for DrivingTableAccessor {
    type Row = Driving;
    type Handle<'db> = DrivingTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.driving()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `driving`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DrivingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DrivingTableHandle`], which mediates access to the table `driving`.
    fn driving(&self) -> DrivingTableHandle<'_>;
}

impl DrivingTableAccess for super::RemoteTables {
    fn driving(&self) -> DrivingTableHandle<'_> {
        DrivingTableHandle {
            imp: self.imp.get_table::<Driving>("driving"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DrivingInsertCallbackId(__sdk::CallbackId);
pub struct DrivingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for DrivingTableHandle<'ctx> {
    type Row = Driving;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Driving> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for DrivingTableHandle<'ctx> {
    type Row = Driving;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Driving> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DrivingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DrivingInsertCallbackId {
        DrivingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DrivingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DrivingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DrivingDeleteCallbackId {
        DrivingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DrivingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for DrivingTableHandle<'ctx> {
    type InsertCallbackId = DrivingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DrivingInsertCallbackId {
        DrivingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DrivingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for DrivingTableHandle<'ctx> {
    type DeleteCallbackId = DrivingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DrivingDeleteCallbackId {
        DrivingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DrivingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DrivingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DrivingTableHandle<'ctx> {
    type UpdateCallbackId = DrivingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DrivingUpdateCallbackId {
        DrivingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DrivingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for DrivingTableHandle<'ctx> {
    type UpdateCallbackId = DrivingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DrivingUpdateCallbackId {
        DrivingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DrivingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `driving`,
/// which allows point queries on the field of the same name
/// via the [`DrivingEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.driving().entity_id().find(...)`.
pub struct DrivingEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Driving, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DrivingTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `driving`.
    pub fn entity_id(&self) -> DrivingEntityIdUnique<'ctx> {
        DrivingEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DrivingEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Driving> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Driving>("driving");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Driving>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Driving>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Driving`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait drivingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Driving`.
    fn driving(&self) -> __sdk::__query_builder::Table<Driving>;
}

impl drivingQueryTableAccess for __sdk::QueryTableAccessor {
    fn driving(&self) -> __sdk::__query_builder::Table<Driving> {
        __sdk::__query_builder::Table::new("driving")
    }
}
