// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FriendAnswerArgs {
    pub request_id: u64,
    pub accept: bool,
}

impl From<FriendAnswerArgs> for super::Reducer {
    fn from(args: FriendAnswerArgs) -> Self {
        Self::FriendAnswer {
            request_id: args.request_id,
            accept: args.accept,
        }
    }
}

impl __sdk::InModule for FriendAnswerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `friend_answer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait friend_answer {
    /// Request that the remote module invoke the reducer `friend_answer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`friend_answer:friend_answer_then`] to run a callback after the reducer completes.
    fn friend_answer(&self, request_id: u64, accept: bool) -> __sdk::Result<()> {
        self.friend_answer_then(request_id, accept, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `friend_answer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn friend_answer_then(
        &self,
        request_id: u64,
        accept: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl friend_answer for super::RemoteReducers {
    fn friend_answer_then(
        &self,
        request_id: u64,
        accept: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(FriendAnswerArgs { request_id, accept }, callback)
    }
}
