// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FriendEntry {
    pub id: u64,
    pub name: String,
    pub online: bool,
    pub level: u32,
    pub job: u16,
    pub zone: String,
}

impl __sdk::InModule for FriendEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FriendEntry`.
///
/// Provides typed access to columns for query building.
pub struct FriendEntryCols {
    pub id: __sdk::__query_builder::Col<FriendEntry, u64>,
    pub name: __sdk::__query_builder::Col<FriendEntry, String>,
    pub online: __sdk::__query_builder::Col<FriendEntry, bool>,
    pub level: __sdk::__query_builder::Col<FriendEntry, u32>,
    pub job: __sdk::__query_builder::Col<FriendEntry, u16>,
    pub zone: __sdk::__query_builder::Col<FriendEntry, String>,
}

impl __sdk::__query_builder::HasCols for FriendEntry {
    type Cols = FriendEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FriendEntryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            online: __sdk::__query_builder::Col::new(table_name, "online"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            job: __sdk::__query_builder::Col::new(table_name, "job"),
            zone: __sdk::__query_builder::Col::new(table_name, "zone"),
        }
    }
}
