// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GiveItemArgs {
    pub name: String,
    pub item_type: u8,
    pub item_number: u16,
    pub quantity: u32,
}

impl From<GiveItemArgs> for super::Reducer {
    fn from(args: GiveItemArgs) -> Self {
        Self::GiveItem {
            name: args.name,
            item_type: args.item_type,
            item_number: args.item_number,
            quantity: args.quantity,
        }
    }
}

impl __sdk::InModule for GiveItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `give_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait give_item {
    /// Request that the remote module invoke the reducer `give_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`give_item:give_item_then`] to run a callback after the reducer completes.
    fn give_item(
        &self,
        name: String,
        item_type: u8,
        item_number: u16,
        quantity: u32,
    ) -> __sdk::Result<()> {
        self.give_item_then(name, item_type, item_number, quantity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `give_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn give_item_then(
        &self,
        name: String,
        item_type: u8,
        item_number: u16,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl give_item for super::RemoteReducers {
    fn give_item_then(
        &self,
        name: String,
        item_type: u8,
        item_number: u16,
        quantity: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GiveItemArgs {
                name,
                item_type,
                item_number,
                quantity,
            },
            callback,
        )
    }
}
