// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GiveSkillArgs {
    pub name: String,
    pub skill_id: u16,
}

impl From<GiveSkillArgs> for super::Reducer {
    fn from(args: GiveSkillArgs) -> Self {
        Self::GiveSkill {
            name: args.name,
            skill_id: args.skill_id,
        }
    }
}

impl __sdk::InModule for GiveSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `give_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait give_skill {
    /// Request that the remote module invoke the reducer `give_skill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`give_skill:give_skill_then`] to run a callback after the reducer completes.
    fn give_skill(&self, name: String, skill_id: u16) -> __sdk::Result<()> {
        self.give_skill_then(name, skill_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `give_skill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn give_skill_then(
        &self,
        name: String,
        skill_id: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl give_skill for super::RemoteReducers {
    fn give_skill_then(
        &self,
        name: String,
        skill_id: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GiveSkillArgs { name, skill_id }, callback)
    }
}
