// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GiveMoneyArgs {
    pub name: String,
    pub amount: i64,
}

impl From<GiveMoneyArgs> for super::Reducer {
    fn from(args: GiveMoneyArgs) -> Self {
        Self::GiveMoney {
            name: args.name,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for GiveMoneyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `give_money`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait give_money {
    /// Request that the remote module invoke the reducer `give_money` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`give_money:give_money_then`] to run a callback after the reducer completes.
    fn give_money(&self, name: String, amount: i64) -> __sdk::Result<()> {
        self.give_money_then(name, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `give_money` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn give_money_then(
        &self,
        name: String,
        amount: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl give_money for super::RemoteReducers {
    fn give_money_then(
        &self,
        name: String,
        amount: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GiveMoneyArgs { name, amount }, callback)
    }
}
