// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GroundItem {
    pub drop_id: u64,
    pub zone_id: u16,
    pub x: f32,
    pub y: f32,
    pub item: String,
    pub owner: Option<__sdk::Identity>,
    pub owner_until_us: i64,
    pub expires_at_us: i64,
}

impl __sdk::InModule for GroundItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GroundItem`.
///
/// Provides typed access to columns for query building.
pub struct GroundItemCols {
    pub drop_id: __sdk::__query_builder::Col<GroundItem, u64>,
    pub zone_id: __sdk::__query_builder::Col<GroundItem, u16>,
    pub x: __sdk::__query_builder::Col<GroundItem, f32>,
    pub y: __sdk::__query_builder::Col<GroundItem, f32>,
    pub item: __sdk::__query_builder::Col<GroundItem, String>,
    pub owner: __sdk::__query_builder::Col<GroundItem, Option<__sdk::Identity>>,
    pub owner_until_us: __sdk::__query_builder::Col<GroundItem, i64>,
    pub expires_at_us: __sdk::__query_builder::Col<GroundItem, i64>,
}

impl __sdk::__query_builder::HasCols for GroundItem {
    type Cols = GroundItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GroundItemCols {
            drop_id: __sdk::__query_builder::Col::new(table_name, "drop_id"),
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            item: __sdk::__query_builder::Col::new(table_name, "item"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            owner_until_us: __sdk::__query_builder::Col::new(table_name, "owner_until_us"),
            expires_at_us: __sdk::__query_builder::Col::new(table_name, "expires_at_us"),
        }
    }
}

/// Indexed column accessor struct for the table `GroundItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct GroundItemIxCols {
    pub drop_id: __sdk::__query_builder::IxCol<GroundItem, u64>,
    pub zone_id: __sdk::__query_builder::IxCol<GroundItem, u16>,
}

impl __sdk::__query_builder::HasIxCols for GroundItem {
    type IxCols = GroundItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GroundItemIxCols {
            drop_id: __sdk::__query_builder::IxCol::new(table_name, "drop_id"),
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GroundItem {}
