// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertGemArgs {
    pub equipment_slot: u8,
    pub page: u8,
    pub index: u16,
}

impl From<InsertGemArgs> for super::Reducer {
    fn from(args: InsertGemArgs) -> Self {
        Self::InsertGem {
            equipment_slot: args.equipment_slot,
            page: args.page,
            index: args.index,
        }
    }
}

impl __sdk::InModule for InsertGemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_gem`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_gem {
    /// Request that the remote module invoke the reducer `insert_gem` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_gem:insert_gem_then`] to run a callback after the reducer completes.
    fn insert_gem(&self, equipment_slot: u8, page: u8, index: u16) -> __sdk::Result<()> {
        self.insert_gem_then(equipment_slot, page, index, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `insert_gem` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_gem_then(
        &self,
        equipment_slot: u8,
        page: u8,
        index: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_gem for super::RemoteReducers {
    fn insert_gem_then(
        &self,
        equipment_slot: u8,
        page: u8,
        index: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            InsertGemArgs {
                equipment_slot,
                page,
                index,
            },
            callback,
        )
    }
}
