// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod add_basic_stat_reducer;
pub mod admin_type;
pub mod attack_reducer;
pub mod begin_game_data_upload_reducer;
pub mod combat_table;
pub mod combat_tick_timer_type;
pub mod combat_type;
pub mod damage_event_table;
pub mod damage_event_type;
pub mod damage_source_type;
pub mod entity_kind_type;
pub mod entity_table;
pub mod entity_type;
pub mod finish_game_data_upload_reducer;
pub mod game_data_status_table;
pub mod game_data_status_type;
pub mod game_file_type;
pub mod game_file_upload_type;
pub mod give_xp_reducer;
pub mod monster_ai_type;
pub mod monster_spawn_type;
pub mod motion_table;
pub mod motion_type;
pub mod move_collision_reducer;
pub mod move_to_reducer;
pub mod place_player_reducer;
pub mod player_table;
pub mod player_type;
pub mod reset_monsters_reducer;
pub mod set_aggro_range_reducer;
pub mod set_loadout_reducer;
pub mod set_name_reducer;
pub mod set_world_rates_reducer;
pub mod spawn_entry_type;
pub mod spawn_tick_timer_type;
pub mod stats_table;
pub mod stats_type;
pub mod stop_reducer;
pub mod tick_stats_table;
pub mod tick_stats_type;
pub mod upload_game_files_reducer;
pub mod world_rates_table;
pub mod world_rates_type;
pub mod xp_event_table;
pub mod xp_event_type;
pub mod zone_info_table;
pub mod zone_info_type;

pub use add_basic_stat_reducer::add_basic_stat;
pub use admin_type::Admin;
pub use attack_reducer::attack;
pub use begin_game_data_upload_reducer::begin_game_data_upload;
pub use combat_table::*;
pub use combat_tick_timer_type::CombatTickTimer;
pub use combat_type::Combat;
pub use damage_event_table::*;
pub use damage_event_type::DamageEvent;
pub use damage_source_type::DamageSource;
pub use entity_kind_type::EntityKind;
pub use entity_table::*;
pub use entity_type::Entity;
pub use finish_game_data_upload_reducer::finish_game_data_upload;
pub use game_data_status_table::*;
pub use game_data_status_type::GameDataStatus;
pub use game_file_type::GameFile;
pub use game_file_upload_type::GameFileUpload;
pub use give_xp_reducer::give_xp;
pub use monster_ai_type::MonsterAi;
pub use monster_spawn_type::MonsterSpawn;
pub use motion_table::*;
pub use motion_type::Motion;
pub use move_collision_reducer::move_collision;
pub use move_to_reducer::move_to;
pub use place_player_reducer::place_player;
pub use player_table::*;
pub use player_type::Player;
pub use reset_monsters_reducer::reset_monsters;
pub use set_aggro_range_reducer::set_aggro_range;
pub use set_loadout_reducer::set_loadout;
pub use set_name_reducer::set_name;
pub use set_world_rates_reducer::set_world_rates;
pub use spawn_entry_type::SpawnEntry;
pub use spawn_tick_timer_type::SpawnTickTimer;
pub use stats_table::*;
pub use stats_type::Stats;
pub use stop_reducer::stop;
pub use tick_stats_table::*;
pub use tick_stats_type::TickStats;
pub use upload_game_files_reducer::upload_game_files;
pub use world_rates_table::*;
pub use world_rates_type::WorldRates;
pub use xp_event_table::*;
pub use xp_event_type::XpEvent;
pub use zone_info_table::*;
pub use zone_info_type::ZoneInfo;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AddBasicStat {
        stat: u8,
    },
    Attack {
        target: u64,
    },
    BeginGameDataUpload,
    FinishGameDataUpload,
    GiveXp {
        name: String,
        xp: u64,
    },
    MoveCollision {
        x: f32,
        y: f32,
    },
    MoveTo {
        x: f32,
        y: f32,
    },
    PlacePlayer {
        name: String,
        x: f32,
        y: f32,
    },
    ResetMonsters,
    SetAggroRange {
        npc_id: u16,
        range: f32,
    },
    SetLoadout {
        ranged: bool,
    },
    SetName {
        name: String,
    },
    SetWorldRates {
        xp_rate: i32,
        drop_rate: i32,
        drop_money_rate: i32,
        reward_rate: i32,
    },
    Stop,
    UploadGameFiles {
        files: Vec<GameFileUpload>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AddBasicStat { .. } => "add_basic_stat",
            Reducer::Attack { .. } => "attack",
            Reducer::BeginGameDataUpload => "begin_game_data_upload",
            Reducer::FinishGameDataUpload => "finish_game_data_upload",
            Reducer::GiveXp { .. } => "give_xp",
            Reducer::MoveCollision { .. } => "move_collision",
            Reducer::MoveTo { .. } => "move_to",
            Reducer::PlacePlayer { .. } => "place_player",
            Reducer::ResetMonsters => "reset_monsters",
            Reducer::SetAggroRange { .. } => "set_aggro_range",
            Reducer::SetLoadout { .. } => "set_loadout",
            Reducer::SetName { .. } => "set_name",
            Reducer::SetWorldRates { .. } => "set_world_rates",
            Reducer::Stop => "stop",
            Reducer::UploadGameFiles { .. } => "upload_game_files",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AddBasicStat { stat } => {
                __sats::bsatn::to_vec(&add_basic_stat_reducer::AddBasicStatArgs {
                    stat: stat.clone(),
                })
            }
            Reducer::Attack { target } => __sats::bsatn::to_vec(&attack_reducer::AttackArgs {
                target: target.clone(),
            }),
            Reducer::BeginGameDataUpload => {
                __sats::bsatn::to_vec(&begin_game_data_upload_reducer::BeginGameDataUploadArgs {})
            }
            Reducer::FinishGameDataUpload => {
                __sats::bsatn::to_vec(&finish_game_data_upload_reducer::FinishGameDataUploadArgs {})
            }
            Reducer::GiveXp { name, xp } => __sats::bsatn::to_vec(&give_xp_reducer::GiveXpArgs {
                name: name.clone(),
                xp: xp.clone(),
            }),
            Reducer::MoveCollision { x, y } => {
                __sats::bsatn::to_vec(&move_collision_reducer::MoveCollisionArgs {
                    x: x.clone(),
                    y: y.clone(),
                })
            }
            Reducer::MoveTo { x, y } => __sats::bsatn::to_vec(&move_to_reducer::MoveToArgs {
                x: x.clone(),
                y: y.clone(),
            }),
            Reducer::PlacePlayer { name, x, y } => {
                __sats::bsatn::to_vec(&place_player_reducer::PlacePlayerArgs {
                    name: name.clone(),
                    x: x.clone(),
                    y: y.clone(),
                })
            }
            Reducer::ResetMonsters => {
                __sats::bsatn::to_vec(&reset_monsters_reducer::ResetMonstersArgs {})
            }
            Reducer::SetAggroRange { npc_id, range } => {
                __sats::bsatn::to_vec(&set_aggro_range_reducer::SetAggroRangeArgs {
                    npc_id: npc_id.clone(),
                    range: range.clone(),
                })
            }
            Reducer::SetLoadout { ranged } => {
                __sats::bsatn::to_vec(&set_loadout_reducer::SetLoadoutArgs {
                    ranged: ranged.clone(),
                })
            }
            Reducer::SetName { name } => {
                __sats::bsatn::to_vec(&set_name_reducer::SetNameArgs { name: name.clone() })
            }
            Reducer::SetWorldRates {
                xp_rate,
                drop_rate,
                drop_money_rate,
                reward_rate,
            } => __sats::bsatn::to_vec(&set_world_rates_reducer::SetWorldRatesArgs {
                xp_rate: xp_rate.clone(),
                drop_rate: drop_rate.clone(),
                drop_money_rate: drop_money_rate.clone(),
                reward_rate: reward_rate.clone(),
            }),
            Reducer::Stop => __sats::bsatn::to_vec(&stop_reducer::StopArgs {}),
            Reducer::UploadGameFiles { files } => {
                __sats::bsatn::to_vec(&upload_game_files_reducer::UploadGameFilesArgs {
                    files: files.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    combat: __sdk::TableUpdate<Combat>,
    damage_event: __sdk::TableUpdate<DamageEvent>,
    entity: __sdk::TableUpdate<Entity>,
    game_data_status: __sdk::TableUpdate<GameDataStatus>,
    motion: __sdk::TableUpdate<Motion>,
    player: __sdk::TableUpdate<Player>,
    stats: __sdk::TableUpdate<Stats>,
    tick_stats: __sdk::TableUpdate<TickStats>,
    world_rates: __sdk::TableUpdate<WorldRates>,
    xp_event: __sdk::TableUpdate<XpEvent>,
    zone_info: __sdk::TableUpdate<ZoneInfo>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "combat" => db_update
                    .combat
                    .append(combat_table::parse_table_update(table_update)?),
                "damage_event" => db_update
                    .damage_event
                    .append(damage_event_table::parse_table_update(table_update)?),
                "entity" => db_update
                    .entity
                    .append(entity_table::parse_table_update(table_update)?),
                "game_data_status" => db_update
                    .game_data_status
                    .append(game_data_status_table::parse_table_update(table_update)?),
                "motion" => db_update
                    .motion
                    .append(motion_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "stats" => db_update
                    .stats
                    .append(stats_table::parse_table_update(table_update)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(tick_stats_table::parse_table_update(table_update)?),
                "world_rates" => db_update
                    .world_rates
                    .append(world_rates_table::parse_table_update(table_update)?),
                "xp_event" => db_update
                    .xp_event
                    .append(xp_event_table::parse_table_update(table_update)?),
                "zone_info" => db_update
                    .zone_info
                    .append(zone_info_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.combat = cache
            .apply_diff_to_table::<Combat>("combat", &self.combat)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.damage_event = self.damage_event.into_event_diff();
        diff.entity = cache
            .apply_diff_to_table::<Entity>("entity", &self.entity)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.game_data_status = cache
            .apply_diff_to_table::<GameDataStatus>("game_data_status", &self.game_data_status)
            .with_updates_by_pk(|row| &row.id);
        diff.motion = cache
            .apply_diff_to_table::<Motion>("motion", &self.motion)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.identity);
        diff.stats = cache
            .apply_diff_to_table::<Stats>("stats", &self.stats)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.tick_stats = cache
            .apply_diff_to_table::<TickStats>("tick_stats", &self.tick_stats)
            .with_updates_by_pk(|row| &row.id);
        diff.world_rates = cache
            .apply_diff_to_table::<WorldRates>("world_rates", &self.world_rates)
            .with_updates_by_pk(|row| &row.id);
        diff.xp_event = self.xp_event.into_event_diff();
        diff.zone_info = cache
            .apply_diff_to_table::<ZoneInfo>("zone_info", &self.zone_info)
            .with_updates_by_pk(|row| &row.zone_id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "combat" => db_update
                    .combat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "damage_event" => db_update
                    .damage_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "entity" => db_update
                    .entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_data_status" => db_update
                    .game_data_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "motion" => db_update
                    .motion
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "stats" => db_update
                    .stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world_rates" => db_update
                    .world_rates
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "xp_event" => db_update
                    .xp_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "zone_info" => db_update
                    .zone_info
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "combat" => db_update
                    .combat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "damage_event" => db_update
                    .damage_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "entity" => db_update
                    .entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_data_status" => db_update
                    .game_data_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "motion" => db_update
                    .motion
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "stats" => db_update
                    .stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world_rates" => db_update
                    .world_rates
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "xp_event" => db_update
                    .xp_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "zone_info" => db_update
                    .zone_info
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    combat: __sdk::TableAppliedDiff<'r, Combat>,
    damage_event: __sdk::TableAppliedDiff<'r, DamageEvent>,
    entity: __sdk::TableAppliedDiff<'r, Entity>,
    game_data_status: __sdk::TableAppliedDiff<'r, GameDataStatus>,
    motion: __sdk::TableAppliedDiff<'r, Motion>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    stats: __sdk::TableAppliedDiff<'r, Stats>,
    tick_stats: __sdk::TableAppliedDiff<'r, TickStats>,
    world_rates: __sdk::TableAppliedDiff<'r, WorldRates>,
    xp_event: __sdk::TableAppliedDiff<'r, XpEvent>,
    zone_info: __sdk::TableAppliedDiff<'r, ZoneInfo>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Combat>("combat", &self.combat, event);
        callbacks.invoke_table_row_callbacks::<DamageEvent>(
            "damage_event",
            &self.damage_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Entity>("entity", &self.entity, event);
        callbacks.invoke_table_row_callbacks::<GameDataStatus>(
            "game_data_status",
            &self.game_data_status,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Motion>("motion", &self.motion, event);
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<Stats>("stats", &self.stats, event);
        callbacks.invoke_table_row_callbacks::<TickStats>("tick_stats", &self.tick_stats, event);
        callbacks.invoke_table_row_callbacks::<WorldRates>("world_rates", &self.world_rates, event);
        callbacks.invoke_table_row_callbacks::<XpEvent>("xp_event", &self.xp_event, event);
        callbacks.invoke_table_row_callbacks::<ZoneInfo>("zone_info", &self.zone_info, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        combat_table::register_table(client_cache);
        damage_event_table::register_table(client_cache);
        entity_table::register_table(client_cache);
        game_data_status_table::register_table(client_cache);
        motion_table::register_table(client_cache);
        player_table::register_table(client_cache);
        stats_table::register_table(client_cache);
        tick_stats_table::register_table(client_cache);
        world_rates_table::register_table(client_cache);
        xp_event_table::register_table(client_cache);
        zone_info_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "combat",
        "damage_event",
        "entity",
        "game_data_status",
        "motion",
        "player",
        "stats",
        "tick_stats",
        "world_rates",
        "xp_event",
        "zone_info",
    ];
}
