// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod abandon_quest_reducer;
pub mod add_basic_stat_reducer;
pub mod admin_clear_quests_reducer;
pub mod admin_give_quest_reducer;
pub mod admin_quest_trigger_reducer;
pub mod admin_set_job_var_reducer;
pub mod admin_teleport_to_npc_reducer;
pub mod admin_type;
pub mod assign_character_reducer;
pub mod attack_reducer;
pub mod auth_config_type;
pub mod bank_deposit_reducer;
pub mod bank_move_reducer;
pub mod bank_table;
pub mod bank_type;
pub mod bank_withdraw_reducer;
pub mod begin_game_data_upload_reducer;
pub mod cast_skill_reducer;
pub mod chat_channel_type;
pub mod chat_limit_type;
pub mod chat_message_type;
pub mod combat_table;
pub mod combat_tick_timer_type;
pub mod combat_type;
pub mod craft_item_reducer;
pub mod craft_slot_type;
pub mod craft_tool_type;
pub mod create_character_reducer;
pub mod damage_event_table;
pub mod damage_event_type;
pub mod damage_source_type;
pub mod disassemble_item_reducer;
pub mod drive_toggle_reducer;
pub mod driving_table;
pub mod driving_type;
pub mod drop_item_reducer;
pub mod drop_money_reducer;
pub mod entity_kind_type;
pub mod entity_table;
pub mod entity_type;
pub mod equip_item_reducer;
pub mod fallen_table;
pub mod fallen_type;
pub mod finish_game_data_upload_reducer;
pub mod friend_answer_reducer;
pub mod friend_ask_reducer;
pub mod friend_entry_type;
pub mod friend_remove_reducer;
pub mod friend_request_type;
pub mod friend_type;
pub mod game_data_status_table;
pub mod game_data_status_type;
pub mod game_file_type;
pub mod game_file_upload_type;
pub mod give_item_reducer;
pub mod give_money_reducer;
pub mod give_skill_reducer;
pub mod give_xp_reducer;
pub mod ground_item_table;
pub mod ground_item_type;
pub mod insert_gem_reducer;
pub mod level_up_skill_reducer;
pub mod monster_ai_type;
pub mod monster_idle_type;
pub mod monster_spawn_type;
pub mod motion_table;
pub mod motion_type;
pub mod move_collision_reducer;
pub mod move_item_reducer;
pub mod move_to_reducer;
pub mod my_chat_table;
pub mod my_friend_requests_table;
pub mod my_friends_table;
pub mod notice_table;
pub mod notice_type;
pub mod npc_cast_motion_table;
pub mod npc_cast_motion_type;
pub mod npc_store_transaction_reducer;
pub mod npc_table;
pub mod npc_type;
pub mod party_accept_reducer;
pub mod party_decline_reducer;
pub mod party_invitation_table;
pub mod party_invite_reducer;
pub mod party_invite_type;
pub mod party_kick_reducer;
pub mod party_leave_reducer;
pub mod party_member_table;
pub mod party_member_type;
pub mod party_set_leader_reducer;
pub mod party_set_rules_reducer;
pub mod party_table;
pub mod party_type;
pub mod personal_store_table;
pub mod personal_store_type;
pub mod pickup_item_reducer;
pub mod place_player_reducer;
pub mod player_table;
pub mod player_type;
pub mod quest_trigger_reducer;
pub mod refine_item_reducer;
pub mod regen_type;
pub mod reset_monsters_reducer;
pub mod revive_player_reducer;
pub mod revive_shield_table;
pub mod revive_shield_type;
pub mod save_point_table;
pub mod save_point_type;
pub mod send_chat_reducer;
pub mod set_aggro_range_reducer;
pub mod set_auth_issuer_reducer;
pub mod set_basic_stat_reducer;
pub mod set_hotbar_slot_reducer;
pub mod set_hp_mp_reducer;
pub mod set_job_reducer;
pub mod set_name_reducer;
pub mod set_npc_variable_reducer;
pub mod set_price_rates_reducer;
pub mod set_save_point_reducer;
pub mod set_world_rates_reducer;
pub mod sit_reducer;
pub mod sitting_table;
pub mod sitting_type;
pub mod skill_cast_table;
pub mod skill_cast_type;
pub mod skill_cooldown_row_type;
pub mod skill_cooldown_table;
pub mod spawn_entry_type;
pub mod spawn_tick_timer_type;
pub mod stats_table;
pub mod stats_type;
pub mod status_effect_row_type;
pub mod status_effect_table;
pub mod stop_reducer;
pub mod store_buy_reducer;
pub mod store_buy_type;
pub mod store_close_reducer;
pub mod store_item_table;
pub mod store_item_type;
pub mod store_listing_type;
pub mod store_open_reducer;
pub mod store_sell_type;
pub mod summon_table;
pub mod summon_type;
pub mod taunt_type;
pub mod tick_stats_table;
pub mod tick_stats_type;
pub mod trade_accept_reducer;
pub mod trade_answer_reducer;
pub mod trade_ask_reducer;
pub mod trade_cancel_reducer;
pub mod trade_lock_reducer;
pub mod trade_offer_reducer;
pub mod trade_request_table;
pub mod trade_request_type;
pub mod trade_slot_type;
pub mod trade_table;
pub mod trade_type;
pub mod unequip_ammo_reducer;
pub mod unequip_item_reducer;
pub mod unequip_vehicle_part_reducer;
pub mod upload_game_files_reducer;
pub mod use_item_reducer;
pub mod use_warp_gate_reducer;
pub mod warp_player_reducer;
pub mod world_rates_table;
pub mod world_rates_type;
pub mod xp_debt_table;
pub mod xp_debt_type;
pub mod xp_event_table;
pub mod xp_event_type;
pub mod zone_info_table;
pub mod zone_info_type;

pub use abandon_quest_reducer::abandon_quest;
pub use add_basic_stat_reducer::add_basic_stat;
pub use admin_clear_quests_reducer::admin_clear_quests;
pub use admin_give_quest_reducer::admin_give_quest;
pub use admin_quest_trigger_reducer::admin_quest_trigger;
pub use admin_set_job_var_reducer::admin_set_job_var;
pub use admin_teleport_to_npc_reducer::admin_teleport_to_npc;
pub use admin_type::Admin;
pub use assign_character_reducer::assign_character;
pub use attack_reducer::attack;
pub use auth_config_type::AuthConfig;
pub use bank_deposit_reducer::bank_deposit;
pub use bank_move_reducer::bank_move;
pub use bank_table::*;
pub use bank_type::Bank;
pub use bank_withdraw_reducer::bank_withdraw;
pub use begin_game_data_upload_reducer::begin_game_data_upload;
pub use cast_skill_reducer::cast_skill;
pub use chat_channel_type::ChatChannel;
pub use chat_limit_type::ChatLimit;
pub use chat_message_type::ChatMessage;
pub use combat_table::*;
pub use combat_tick_timer_type::CombatTickTimer;
pub use combat_type::Combat;
pub use craft_item_reducer::craft_item;
pub use craft_slot_type::CraftSlot;
pub use craft_tool_type::CraftTool;
pub use create_character_reducer::create_character;
pub use damage_event_table::*;
pub use damage_event_type::DamageEvent;
pub use damage_source_type::DamageSource;
pub use disassemble_item_reducer::disassemble_item;
pub use drive_toggle_reducer::drive_toggle;
pub use driving_table::*;
pub use driving_type::Driving;
pub use drop_item_reducer::drop_item;
pub use drop_money_reducer::drop_money;
pub use entity_kind_type::EntityKind;
pub use entity_table::*;
pub use entity_type::Entity;
pub use equip_item_reducer::equip_item;
pub use fallen_table::*;
pub use fallen_type::Fallen;
pub use finish_game_data_upload_reducer::finish_game_data_upload;
pub use friend_answer_reducer::friend_answer;
pub use friend_ask_reducer::friend_ask;
pub use friend_entry_type::FriendEntry;
pub use friend_remove_reducer::friend_remove;
pub use friend_request_type::FriendRequest;
pub use friend_type::Friend;
pub use game_data_status_table::*;
pub use game_data_status_type::GameDataStatus;
pub use game_file_type::GameFile;
pub use game_file_upload_type::GameFileUpload;
pub use give_item_reducer::give_item;
pub use give_money_reducer::give_money;
pub use give_skill_reducer::give_skill;
pub use give_xp_reducer::give_xp;
pub use ground_item_table::*;
pub use ground_item_type::GroundItem;
pub use insert_gem_reducer::insert_gem;
pub use level_up_skill_reducer::level_up_skill;
pub use monster_ai_type::MonsterAi;
pub use monster_idle_type::MonsterIdle;
pub use monster_spawn_type::MonsterSpawn;
pub use motion_table::*;
pub use motion_type::Motion;
pub use move_collision_reducer::move_collision;
pub use move_item_reducer::move_item;
pub use move_to_reducer::move_to;
pub use my_chat_table::*;
pub use my_friend_requests_table::*;
pub use my_friends_table::*;
pub use notice_table::*;
pub use notice_type::Notice;
pub use npc_cast_motion_table::*;
pub use npc_cast_motion_type::NpcCastMotion;
pub use npc_store_transaction_reducer::npc_store_transaction;
pub use npc_table::*;
pub use npc_type::Npc;
pub use party_accept_reducer::party_accept;
pub use party_decline_reducer::party_decline;
pub use party_invitation_table::*;
pub use party_invite_reducer::party_invite;
pub use party_invite_type::PartyInvite;
pub use party_kick_reducer::party_kick;
pub use party_leave_reducer::party_leave;
pub use party_member_table::*;
pub use party_member_type::PartyMember;
pub use party_set_leader_reducer::party_set_leader;
pub use party_set_rules_reducer::party_set_rules;
pub use party_table::*;
pub use party_type::Party;
pub use personal_store_table::*;
pub use personal_store_type::PersonalStore;
pub use pickup_item_reducer::pickup_item;
pub use place_player_reducer::place_player;
pub use player_table::*;
pub use player_type::Player;
pub use quest_trigger_reducer::quest_trigger;
pub use refine_item_reducer::refine_item;
pub use regen_type::Regen;
pub use reset_monsters_reducer::reset_monsters;
pub use revive_player_reducer::revive_player;
pub use revive_shield_table::*;
pub use revive_shield_type::ReviveShield;
pub use save_point_table::*;
pub use save_point_type::SavePoint;
pub use send_chat_reducer::send_chat;
pub use set_aggro_range_reducer::set_aggro_range;
pub use set_auth_issuer_reducer::set_auth_issuer;
pub use set_basic_stat_reducer::set_basic_stat;
pub use set_hotbar_slot_reducer::set_hotbar_slot;
pub use set_hp_mp_reducer::set_hp_mp;
pub use set_job_reducer::set_job;
pub use set_name_reducer::set_name;
pub use set_npc_variable_reducer::set_npc_variable;
pub use set_price_rates_reducer::set_price_rates;
pub use set_save_point_reducer::set_save_point;
pub use set_world_rates_reducer::set_world_rates;
pub use sit_reducer::sit;
pub use sitting_table::*;
pub use sitting_type::Sitting;
pub use skill_cast_table::*;
pub use skill_cast_type::SkillCast;
pub use skill_cooldown_row_type::SkillCooldownRow;
pub use skill_cooldown_table::*;
pub use spawn_entry_type::SpawnEntry;
pub use spawn_tick_timer_type::SpawnTickTimer;
pub use stats_table::*;
pub use stats_type::Stats;
pub use status_effect_row_type::StatusEffectRow;
pub use status_effect_table::*;
pub use stop_reducer::stop;
pub use store_buy_reducer::store_buy;
pub use store_buy_type::StoreBuy;
pub use store_close_reducer::store_close;
pub use store_item_table::*;
pub use store_item_type::StoreItem;
pub use store_listing_type::StoreListing;
pub use store_open_reducer::store_open;
pub use store_sell_type::StoreSell;
pub use summon_table::*;
pub use summon_type::Summon;
pub use taunt_type::Taunt;
pub use tick_stats_table::*;
pub use tick_stats_type::TickStats;
pub use trade_accept_reducer::trade_accept;
pub use trade_answer_reducer::trade_answer;
pub use trade_ask_reducer::trade_ask;
pub use trade_cancel_reducer::trade_cancel;
pub use trade_lock_reducer::trade_lock;
pub use trade_offer_reducer::trade_offer;
pub use trade_request_table::*;
pub use trade_request_type::TradeRequest;
pub use trade_slot_type::TradeSlot;
pub use trade_table::*;
pub use trade_type::Trade;
pub use unequip_ammo_reducer::unequip_ammo;
pub use unequip_item_reducer::unequip_item;
pub use unequip_vehicle_part_reducer::unequip_vehicle_part;
pub use upload_game_files_reducer::upload_game_files;
pub use use_item_reducer::use_item;
pub use use_warp_gate_reducer::use_warp_gate;
pub use warp_player_reducer::warp_player;
pub use world_rates_table::*;
pub use world_rates_type::WorldRates;
pub use xp_debt_table::*;
pub use xp_debt_type::XpDebt;
pub use xp_event_table::*;
pub use xp_event_type::XpEvent;
pub use zone_info_table::*;
pub use zone_info_type::ZoneInfo;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AbandonQuest {
        slot: u8,
        quest_id: u32,
    },
    AddBasicStat {
        stat: u8,
    },
    AdminClearQuests {
        player_name: String,
    },
    AdminGiveQuest {
        player_name: String,
        quest_id: u32,
        item_number: u32,
        quantity: u32,
    },
    AdminQuestTrigger {
        player_name: String,
        trigger: String,
    },
    AdminSetJobVar {
        player_name: String,
        index: u32,
        value: u16,
    },
    AdminTeleportToNpc {
        name: String,
        npc_id: u16,
    },
    AssignCharacter {
        name: String,
        account: __sdk::Identity,
    },
    Attack {
        target: u64,
    },
    BankDeposit {
        npc_entity_id: u64,
        page: u8,
        index: u16,
        quantity: u32,
    },
    BankMove {
        from: u16,
        to: u16,
    },
    BankWithdraw {
        npc_entity_id: u64,
        slot: u16,
        quantity: u32,
    },
    BeginGameDataUpload,
    CastSkill {
        page: u8,
        index: u16,
        target: Option<u64>,
        x: f32,
        y: f32,
    },
    CraftItem {
        skill_page: u8,
        skill_index: u16,
        item_type_number: u8,
        item_number: u16,
        materials: Vec<CraftSlot>,
    },
    CreateCharacter {
        name: String,
        gender: u8,
        face: u8,
        hair: u8,
    },
    DisassembleItem {
        tool: CraftTool,
        page: u8,
        index: u16,
    },
    DriveToggle,
    DropItem {
        page: u8,
        index: u16,
        quantity: u32,
    },
    DropMoney {
        amount: i64,
    },
    EquipItem {
        page: u8,
        index: u16,
    },
    FinishGameDataUpload,
    FriendAnswer {
        request_id: u64,
        accept: bool,
    },
    FriendAsk {
        name: String,
    },
    FriendRemove {
        name: String,
    },
    GiveItem {
        name: String,
        item_type: u8,
        item_number: u16,
        quantity: u32,
    },
    GiveMoney {
        name: String,
        amount: i64,
    },
    GiveSkill {
        name: String,
        skill_id: u16,
    },
    GiveXp {
        name: String,
        xp: u64,
    },
    InsertGem {
        equipment_slot: u8,
        page: u8,
        index: u16,
    },
    LevelUpSkill {
        page: u8,
        index: u16,
    },
    MoveCollision {
        x: f32,
        y: f32,
    },
    MoveItem {
        page: u8,
        from: u16,
        to: u16,
    },
    MoveTo {
        x: f32,
        y: f32,
    },
    NpcStoreTransaction {
        npc_entity_id: u64,
        buy: Vec<StoreBuy>,
        sell: Vec<StoreSell>,
    },
    PartyAccept {
        invite_id: u64,
    },
    PartyDecline {
        invite_id: u64,
    },
    PartyInvite {
        target_entity_id: u64,
    },
    PartyKick {
        member: __sdk::Identity,
    },
    PartyLeave,
    PartySetLeader {
        member: __sdk::Identity,
    },
    PartySetRules {
        xp_sharing: u8,
        item_sharing: u8,
    },
    PickupItem {
        drop_id: u64,
    },
    PlacePlayer {
        name: String,
        x: f32,
        y: f32,
    },
    QuestTrigger {
        name: String,
    },
    RefineItem {
        tool: CraftTool,
        page: u8,
        index: u16,
        materials: Vec<CraftSlot>,
    },
    ResetMonsters,
    RevivePlayer {
        at_save_point: bool,
    },
    SendChat {
        channel: ChatChannel,
        to: String,
        text: String,
    },
    SetAggroRange {
        npc_id: u16,
        range: f32,
    },
    SetAuthIssuer {
        issuer: String,
    },
    SetBasicStat {
        name: String,
        stat: u8,
        value: i32,
    },
    SetHotbarSlot {
        index: u8,
        kind: u8,
        page: u8,
        slot: u16,
    },
    SetHpMp {
        name: String,
        hp: i32,
        mp: i32,
    },
    SetJob {
        name: String,
        job: u16,
    },
    SetName {
        name: String,
    },
    SetNpcVariable {
        npc_id: u16,
        variable_id: u8,
        value: i32,
    },
    SetPriceRates {
        world_price_rate: i32,
        item_price_rate: i32,
        town_price_rate: i32,
    },
    SetSavePoint,
    SetWorldRates {
        xp_rate: i32,
        drop_rate: i32,
        drop_money_rate: i32,
        reward_rate: i32,
    },
    Sit,
    Stop,
    StoreBuy {
        store_entity: u64,
        store_item_id: u64,
        quantity: u32,
    },
    StoreClose,
    StoreOpen {
        title: String,
        listings: Vec<StoreListing>,
    },
    TradeAccept,
    TradeAnswer {
        request_id: u64,
        accept: bool,
    },
    TradeAsk {
        target_entity_id: u64,
    },
    TradeCancel,
    TradeLock {
        locked: bool,
    },
    TradeOffer {
        slots: Vec<TradeSlot>,
        money: i64,
    },
    UnequipAmmo {
        ammo_slot: u8,
    },
    UnequipItem {
        equipment_slot: u8,
    },
    UnequipVehiclePart {
        part: u8,
    },
    UploadGameFiles {
        files: Vec<GameFileUpload>,
    },
    UseItem {
        page: u8,
        index: u16,
    },
    UseWarpGate {
        warp_id: u16,
    },
    WarpPlayer {
        name: String,
        zone_id: u16,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AbandonQuest { .. } => "abandon_quest",
            Reducer::AddBasicStat { .. } => "add_basic_stat",
            Reducer::AdminClearQuests { .. } => "admin_clear_quests",
            Reducer::AdminGiveQuest { .. } => "admin_give_quest",
            Reducer::AdminQuestTrigger { .. } => "admin_quest_trigger",
            Reducer::AdminSetJobVar { .. } => "admin_set_job_var",
            Reducer::AdminTeleportToNpc { .. } => "admin_teleport_to_npc",
            Reducer::AssignCharacter { .. } => "assign_character",
            Reducer::Attack { .. } => "attack",
            Reducer::BankDeposit { .. } => "bank_deposit",
            Reducer::BankMove { .. } => "bank_move",
            Reducer::BankWithdraw { .. } => "bank_withdraw",
            Reducer::BeginGameDataUpload => "begin_game_data_upload",
            Reducer::CastSkill { .. } => "cast_skill",
            Reducer::CraftItem { .. } => "craft_item",
            Reducer::CreateCharacter { .. } => "create_character",
            Reducer::DisassembleItem { .. } => "disassemble_item",
            Reducer::DriveToggle => "drive_toggle",
            Reducer::DropItem { .. } => "drop_item",
            Reducer::DropMoney { .. } => "drop_money",
            Reducer::EquipItem { .. } => "equip_item",
            Reducer::FinishGameDataUpload => "finish_game_data_upload",
            Reducer::FriendAnswer { .. } => "friend_answer",
            Reducer::FriendAsk { .. } => "friend_ask",
            Reducer::FriendRemove { .. } => "friend_remove",
            Reducer::GiveItem { .. } => "give_item",
            Reducer::GiveMoney { .. } => "give_money",
            Reducer::GiveSkill { .. } => "give_skill",
            Reducer::GiveXp { .. } => "give_xp",
            Reducer::InsertGem { .. } => "insert_gem",
            Reducer::LevelUpSkill { .. } => "level_up_skill",
            Reducer::MoveCollision { .. } => "move_collision",
            Reducer::MoveItem { .. } => "move_item",
            Reducer::MoveTo { .. } => "move_to",
            Reducer::NpcStoreTransaction { .. } => "npc_store_transaction",
            Reducer::PartyAccept { .. } => "party_accept",
            Reducer::PartyDecline { .. } => "party_decline",
            Reducer::PartyInvite { .. } => "party_invite",
            Reducer::PartyKick { .. } => "party_kick",
            Reducer::PartyLeave => "party_leave",
            Reducer::PartySetLeader { .. } => "party_set_leader",
            Reducer::PartySetRules { .. } => "party_set_rules",
            Reducer::PickupItem { .. } => "pickup_item",
            Reducer::PlacePlayer { .. } => "place_player",
            Reducer::QuestTrigger { .. } => "quest_trigger",
            Reducer::RefineItem { .. } => "refine_item",
            Reducer::ResetMonsters => "reset_monsters",
            Reducer::RevivePlayer { .. } => "revive_player",
            Reducer::SendChat { .. } => "send_chat",
            Reducer::SetAggroRange { .. } => "set_aggro_range",
            Reducer::SetAuthIssuer { .. } => "set_auth_issuer",
            Reducer::SetBasicStat { .. } => "set_basic_stat",
            Reducer::SetHotbarSlot { .. } => "set_hotbar_slot",
            Reducer::SetHpMp { .. } => "set_hp_mp",
            Reducer::SetJob { .. } => "set_job",
            Reducer::SetName { .. } => "set_name",
            Reducer::SetNpcVariable { .. } => "set_npc_variable",
            Reducer::SetPriceRates { .. } => "set_price_rates",
            Reducer::SetSavePoint => "set_save_point",
            Reducer::SetWorldRates { .. } => "set_world_rates",
            Reducer::Sit => "sit",
            Reducer::Stop => "stop",
            Reducer::StoreBuy { .. } => "store_buy",
            Reducer::StoreClose => "store_close",
            Reducer::StoreOpen { .. } => "store_open",
            Reducer::TradeAccept => "trade_accept",
            Reducer::TradeAnswer { .. } => "trade_answer",
            Reducer::TradeAsk { .. } => "trade_ask",
            Reducer::TradeCancel => "trade_cancel",
            Reducer::TradeLock { .. } => "trade_lock",
            Reducer::TradeOffer { .. } => "trade_offer",
            Reducer::UnequipAmmo { .. } => "unequip_ammo",
            Reducer::UnequipItem { .. } => "unequip_item",
            Reducer::UnequipVehiclePart { .. } => "unequip_vehicle_part",
            Reducer::UploadGameFiles { .. } => "upload_game_files",
            Reducer::UseItem { .. } => "use_item",
            Reducer::UseWarpGate { .. } => "use_warp_gate",
            Reducer::WarpPlayer { .. } => "warp_player",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AbandonQuest { slot, quest_id } => {
                __sats::bsatn::to_vec(&abandon_quest_reducer::AbandonQuestArgs {
                    slot: slot.clone(),
                    quest_id: quest_id.clone(),
                })
            }
            Reducer::AddBasicStat { stat } => {
                __sats::bsatn::to_vec(&add_basic_stat_reducer::AddBasicStatArgs {
                    stat: stat.clone(),
                })
            }
            Reducer::AdminClearQuests { player_name } => {
                __sats::bsatn::to_vec(&admin_clear_quests_reducer::AdminClearQuestsArgs {
                    player_name: player_name.clone(),
                })
            }
            Reducer::AdminGiveQuest {
                player_name,
                quest_id,
                item_number,
                quantity,
            } => __sats::bsatn::to_vec(&admin_give_quest_reducer::AdminGiveQuestArgs {
                player_name: player_name.clone(),
                quest_id: quest_id.clone(),
                item_number: item_number.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::AdminQuestTrigger {
                player_name,
                trigger,
            } => __sats::bsatn::to_vec(&admin_quest_trigger_reducer::AdminQuestTriggerArgs {
                player_name: player_name.clone(),
                trigger: trigger.clone(),
            }),
            Reducer::AdminSetJobVar {
                player_name,
                index,
                value,
            } => __sats::bsatn::to_vec(&admin_set_job_var_reducer::AdminSetJobVarArgs {
                player_name: player_name.clone(),
                index: index.clone(),
                value: value.clone(),
            }),
            Reducer::AdminTeleportToNpc { name, npc_id } => {
                __sats::bsatn::to_vec(&admin_teleport_to_npc_reducer::AdminTeleportToNpcArgs {
                    name: name.clone(),
                    npc_id: npc_id.clone(),
                })
            }
            Reducer::AssignCharacter { name, account } => {
                __sats::bsatn::to_vec(&assign_character_reducer::AssignCharacterArgs {
                    name: name.clone(),
                    account: account.clone(),
                })
            }
            Reducer::Attack { target } => __sats::bsatn::to_vec(&attack_reducer::AttackArgs {
                target: target.clone(),
            }),
            Reducer::BankDeposit {
                npc_entity_id,
                page,
                index,
                quantity,
            } => __sats::bsatn::to_vec(&bank_deposit_reducer::BankDepositArgs {
                npc_entity_id: npc_entity_id.clone(),
                page: page.clone(),
                index: index.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::BankMove { from, to } => {
                __sats::bsatn::to_vec(&bank_move_reducer::BankMoveArgs {
                    from: from.clone(),
                    to: to.clone(),
                })
            }
            Reducer::BankWithdraw {
                npc_entity_id,
                slot,
                quantity,
            } => __sats::bsatn::to_vec(&bank_withdraw_reducer::BankWithdrawArgs {
                npc_entity_id: npc_entity_id.clone(),
                slot: slot.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::BeginGameDataUpload => {
                __sats::bsatn::to_vec(&begin_game_data_upload_reducer::BeginGameDataUploadArgs {})
            }
            Reducer::CastSkill {
                page,
                index,
                target,
                x,
                y,
            } => __sats::bsatn::to_vec(&cast_skill_reducer::CastSkillArgs {
                page: page.clone(),
                index: index.clone(),
                target: target.clone(),
                x: x.clone(),
                y: y.clone(),
            }),
            Reducer::CraftItem {
                skill_page,
                skill_index,
                item_type_number,
                item_number,
                materials,
            } => __sats::bsatn::to_vec(&craft_item_reducer::CraftItemArgs {
                skill_page: skill_page.clone(),
                skill_index: skill_index.clone(),
                item_type_number: item_type_number.clone(),
                item_number: item_number.clone(),
                materials: materials.clone(),
            }),
            Reducer::CreateCharacter {
                name,
                gender,
                face,
                hair,
            } => __sats::bsatn::to_vec(&create_character_reducer::CreateCharacterArgs {
                name: name.clone(),
                gender: gender.clone(),
                face: face.clone(),
                hair: hair.clone(),
            }),
            Reducer::DisassembleItem { tool, page, index } => {
                __sats::bsatn::to_vec(&disassemble_item_reducer::DisassembleItemArgs {
                    tool: tool.clone(),
                    page: page.clone(),
                    index: index.clone(),
                })
            }
            Reducer::DriveToggle => {
                __sats::bsatn::to_vec(&drive_toggle_reducer::DriveToggleArgs {})
            }
            Reducer::DropItem {
                page,
                index,
                quantity,
            } => __sats::bsatn::to_vec(&drop_item_reducer::DropItemArgs {
                page: page.clone(),
                index: index.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::DropMoney { amount } => {
                __sats::bsatn::to_vec(&drop_money_reducer::DropMoneyArgs {
                    amount: amount.clone(),
                })
            }
            Reducer::EquipItem { page, index } => {
                __sats::bsatn::to_vec(&equip_item_reducer::EquipItemArgs {
                    page: page.clone(),
                    index: index.clone(),
                })
            }
            Reducer::FinishGameDataUpload => {
                __sats::bsatn::to_vec(&finish_game_data_upload_reducer::FinishGameDataUploadArgs {})
            }
            Reducer::FriendAnswer { request_id, accept } => {
                __sats::bsatn::to_vec(&friend_answer_reducer::FriendAnswerArgs {
                    request_id: request_id.clone(),
                    accept: accept.clone(),
                })
            }
            Reducer::FriendAsk { name } => {
                __sats::bsatn::to_vec(&friend_ask_reducer::FriendAskArgs { name: name.clone() })
            }
            Reducer::FriendRemove { name } => {
                __sats::bsatn::to_vec(&friend_remove_reducer::FriendRemoveArgs {
                    name: name.clone(),
                })
            }
            Reducer::GiveItem {
                name,
                item_type,
                item_number,
                quantity,
            } => __sats::bsatn::to_vec(&give_item_reducer::GiveItemArgs {
                name: name.clone(),
                item_type: item_type.clone(),
                item_number: item_number.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::GiveMoney { name, amount } => {
                __sats::bsatn::to_vec(&give_money_reducer::GiveMoneyArgs {
                    name: name.clone(),
                    amount: amount.clone(),
                })
            }
            Reducer::GiveSkill { name, skill_id } => {
                __sats::bsatn::to_vec(&give_skill_reducer::GiveSkillArgs {
                    name: name.clone(),
                    skill_id: skill_id.clone(),
                })
            }
            Reducer::GiveXp { name, xp } => __sats::bsatn::to_vec(&give_xp_reducer::GiveXpArgs {
                name: name.clone(),
                xp: xp.clone(),
            }),
            Reducer::InsertGem {
                equipment_slot,
                page,
                index,
            } => __sats::bsatn::to_vec(&insert_gem_reducer::InsertGemArgs {
                equipment_slot: equipment_slot.clone(),
                page: page.clone(),
                index: index.clone(),
            }),
            Reducer::LevelUpSkill { page, index } => {
                __sats::bsatn::to_vec(&level_up_skill_reducer::LevelUpSkillArgs {
                    page: page.clone(),
                    index: index.clone(),
                })
            }
            Reducer::MoveCollision { x, y } => {
                __sats::bsatn::to_vec(&move_collision_reducer::MoveCollisionArgs {
                    x: x.clone(),
                    y: y.clone(),
                })
            }
            Reducer::MoveItem { page, from, to } => {
                __sats::bsatn::to_vec(&move_item_reducer::MoveItemArgs {
                    page: page.clone(),
                    from: from.clone(),
                    to: to.clone(),
                })
            }
            Reducer::MoveTo { x, y } => __sats::bsatn::to_vec(&move_to_reducer::MoveToArgs {
                x: x.clone(),
                y: y.clone(),
            }),
            Reducer::NpcStoreTransaction {
                npc_entity_id,
                buy,
                sell,
            } => __sats::bsatn::to_vec(&npc_store_transaction_reducer::NpcStoreTransactionArgs {
                npc_entity_id: npc_entity_id.clone(),
                buy: buy.clone(),
                sell: sell.clone(),
            }),
            Reducer::PartyAccept { invite_id } => {
                __sats::bsatn::to_vec(&party_accept_reducer::PartyAcceptArgs {
                    invite_id: invite_id.clone(),
                })
            }
            Reducer::PartyDecline { invite_id } => {
                __sats::bsatn::to_vec(&party_decline_reducer::PartyDeclineArgs {
                    invite_id: invite_id.clone(),
                })
            }
            Reducer::PartyInvite { target_entity_id } => {
                __sats::bsatn::to_vec(&party_invite_reducer::PartyInviteArgs {
                    target_entity_id: target_entity_id.clone(),
                })
            }
            Reducer::PartyKick { member } => {
                __sats::bsatn::to_vec(&party_kick_reducer::PartyKickArgs {
                    member: member.clone(),
                })
            }
            Reducer::PartyLeave => __sats::bsatn::to_vec(&party_leave_reducer::PartyLeaveArgs {}),
            Reducer::PartySetLeader { member } => {
                __sats::bsatn::to_vec(&party_set_leader_reducer::PartySetLeaderArgs {
                    member: member.clone(),
                })
            }
            Reducer::PartySetRules {
                xp_sharing,
                item_sharing,
            } => __sats::bsatn::to_vec(&party_set_rules_reducer::PartySetRulesArgs {
                xp_sharing: xp_sharing.clone(),
                item_sharing: item_sharing.clone(),
            }),
            Reducer::PickupItem { drop_id } => {
                __sats::bsatn::to_vec(&pickup_item_reducer::PickupItemArgs {
                    drop_id: drop_id.clone(),
                })
            }
            Reducer::PlacePlayer { name, x, y } => {
                __sats::bsatn::to_vec(&place_player_reducer::PlacePlayerArgs {
                    name: name.clone(),
                    x: x.clone(),
                    y: y.clone(),
                })
            }
            Reducer::QuestTrigger { name } => {
                __sats::bsatn::to_vec(&quest_trigger_reducer::QuestTriggerArgs {
                    name: name.clone(),
                })
            }
            Reducer::RefineItem {
                tool,
                page,
                index,
                materials,
            } => __sats::bsatn::to_vec(&refine_item_reducer::RefineItemArgs {
                tool: tool.clone(),
                page: page.clone(),
                index: index.clone(),
                materials: materials.clone(),
            }),
            Reducer::ResetMonsters => {
                __sats::bsatn::to_vec(&reset_monsters_reducer::ResetMonstersArgs {})
            }
            Reducer::RevivePlayer { at_save_point } => {
                __sats::bsatn::to_vec(&revive_player_reducer::RevivePlayerArgs {
                    at_save_point: at_save_point.clone(),
                })
            }
            Reducer::SendChat { channel, to, text } => {
                __sats::bsatn::to_vec(&send_chat_reducer::SendChatArgs {
                    channel: channel.clone(),
                    to: to.clone(),
                    text: text.clone(),
                })
            }
            Reducer::SetAggroRange { npc_id, range } => {
                __sats::bsatn::to_vec(&set_aggro_range_reducer::SetAggroRangeArgs {
                    npc_id: npc_id.clone(),
                    range: range.clone(),
                })
            }
            Reducer::SetAuthIssuer { issuer } => {
                __sats::bsatn::to_vec(&set_auth_issuer_reducer::SetAuthIssuerArgs {
                    issuer: issuer.clone(),
                })
            }
            Reducer::SetBasicStat { name, stat, value } => {
                __sats::bsatn::to_vec(&set_basic_stat_reducer::SetBasicStatArgs {
                    name: name.clone(),
                    stat: stat.clone(),
                    value: value.clone(),
                })
            }
            Reducer::SetHotbarSlot {
                index,
                kind,
                page,
                slot,
            } => __sats::bsatn::to_vec(&set_hotbar_slot_reducer::SetHotbarSlotArgs {
                index: index.clone(),
                kind: kind.clone(),
                page: page.clone(),
                slot: slot.clone(),
            }),
            Reducer::SetHpMp { name, hp, mp } => {
                __sats::bsatn::to_vec(&set_hp_mp_reducer::SetHpMpArgs {
                    name: name.clone(),
                    hp: hp.clone(),
                    mp: mp.clone(),
                })
            }
            Reducer::SetJob { name, job } => __sats::bsatn::to_vec(&set_job_reducer::SetJobArgs {
                name: name.clone(),
                job: job.clone(),
            }),
            Reducer::SetName { name } => {
                __sats::bsatn::to_vec(&set_name_reducer::SetNameArgs { name: name.clone() })
            }
            Reducer::SetNpcVariable {
                npc_id,
                variable_id,
                value,
            } => __sats::bsatn::to_vec(&set_npc_variable_reducer::SetNpcVariableArgs {
                npc_id: npc_id.clone(),
                variable_id: variable_id.clone(),
                value: value.clone(),
            }),
            Reducer::SetPriceRates {
                world_price_rate,
                item_price_rate,
                town_price_rate,
            } => __sats::bsatn::to_vec(&set_price_rates_reducer::SetPriceRatesArgs {
                world_price_rate: world_price_rate.clone(),
                item_price_rate: item_price_rate.clone(),
                town_price_rate: town_price_rate.clone(),
            }),
            Reducer::SetSavePoint => {
                __sats::bsatn::to_vec(&set_save_point_reducer::SetSavePointArgs {})
            }
            Reducer::SetWorldRates {
                xp_rate,
                drop_rate,
                drop_money_rate,
                reward_rate,
            } => __sats::bsatn::to_vec(&set_world_rates_reducer::SetWorldRatesArgs {
                xp_rate: xp_rate.clone(),
                drop_rate: drop_rate.clone(),
                drop_money_rate: drop_money_rate.clone(),
                reward_rate: reward_rate.clone(),
            }),
            Reducer::Sit => __sats::bsatn::to_vec(&sit_reducer::SitArgs {}),
            Reducer::Stop => __sats::bsatn::to_vec(&stop_reducer::StopArgs {}),
            Reducer::StoreBuy {
                store_entity,
                store_item_id,
                quantity,
            } => __sats::bsatn::to_vec(&store_buy_reducer::StoreBuyArgs {
                store_entity: store_entity.clone(),
                store_item_id: store_item_id.clone(),
                quantity: quantity.clone(),
            }),
            Reducer::StoreClose => __sats::bsatn::to_vec(&store_close_reducer::StoreCloseArgs {}),
            Reducer::StoreOpen { title, listings } => {
                __sats::bsatn::to_vec(&store_open_reducer::StoreOpenArgs {
                    title: title.clone(),
                    listings: listings.clone(),
                })
            }
            Reducer::TradeAccept => {
                __sats::bsatn::to_vec(&trade_accept_reducer::TradeAcceptArgs {})
            }
            Reducer::TradeAnswer { request_id, accept } => {
                __sats::bsatn::to_vec(&trade_answer_reducer::TradeAnswerArgs {
                    request_id: request_id.clone(),
                    accept: accept.clone(),
                })
            }
            Reducer::TradeAsk { target_entity_id } => {
                __sats::bsatn::to_vec(&trade_ask_reducer::TradeAskArgs {
                    target_entity_id: target_entity_id.clone(),
                })
            }
            Reducer::TradeCancel => {
                __sats::bsatn::to_vec(&trade_cancel_reducer::TradeCancelArgs {})
            }
            Reducer::TradeLock { locked } => {
                __sats::bsatn::to_vec(&trade_lock_reducer::TradeLockArgs {
                    locked: locked.clone(),
                })
            }
            Reducer::TradeOffer { slots, money } => {
                __sats::bsatn::to_vec(&trade_offer_reducer::TradeOfferArgs {
                    slots: slots.clone(),
                    money: money.clone(),
                })
            }
            Reducer::UnequipAmmo { ammo_slot } => {
                __sats::bsatn::to_vec(&unequip_ammo_reducer::UnequipAmmoArgs {
                    ammo_slot: ammo_slot.clone(),
                })
            }
            Reducer::UnequipItem { equipment_slot } => {
                __sats::bsatn::to_vec(&unequip_item_reducer::UnequipItemArgs {
                    equipment_slot: equipment_slot.clone(),
                })
            }
            Reducer::UnequipVehiclePart { part } => {
                __sats::bsatn::to_vec(&unequip_vehicle_part_reducer::UnequipVehiclePartArgs {
                    part: part.clone(),
                })
            }
            Reducer::UploadGameFiles { files } => {
                __sats::bsatn::to_vec(&upload_game_files_reducer::UploadGameFilesArgs {
                    files: files.clone(),
                })
            }
            Reducer::UseItem { page, index } => {
                __sats::bsatn::to_vec(&use_item_reducer::UseItemArgs {
                    page: page.clone(),
                    index: index.clone(),
                })
            }
            Reducer::UseWarpGate { warp_id } => {
                __sats::bsatn::to_vec(&use_warp_gate_reducer::UseWarpGateArgs {
                    warp_id: warp_id.clone(),
                })
            }
            Reducer::WarpPlayer { name, zone_id } => {
                __sats::bsatn::to_vec(&warp_player_reducer::WarpPlayerArgs {
                    name: name.clone(),
                    zone_id: zone_id.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    bank: __sdk::TableUpdate<Bank>,
    combat: __sdk::TableUpdate<Combat>,
    damage_event: __sdk::TableUpdate<DamageEvent>,
    driving: __sdk::TableUpdate<Driving>,
    entity: __sdk::TableUpdate<Entity>,
    fallen: __sdk::TableUpdate<Fallen>,
    game_data_status: __sdk::TableUpdate<GameDataStatus>,
    ground_item: __sdk::TableUpdate<GroundItem>,
    motion: __sdk::TableUpdate<Motion>,
    my_chat: __sdk::TableUpdate<ChatMessage>,
    my_friend_requests: __sdk::TableUpdate<FriendRequest>,
    my_friends: __sdk::TableUpdate<FriendEntry>,
    notice: __sdk::TableUpdate<Notice>,
    npc: __sdk::TableUpdate<Npc>,
    npc_cast_motion: __sdk::TableUpdate<NpcCastMotion>,
    party: __sdk::TableUpdate<Party>,
    party_invitation: __sdk::TableUpdate<PartyInvite>,
    party_member: __sdk::TableUpdate<PartyMember>,
    personal_store: __sdk::TableUpdate<PersonalStore>,
    player: __sdk::TableUpdate<Player>,
    revive_shield: __sdk::TableUpdate<ReviveShield>,
    save_point: __sdk::TableUpdate<SavePoint>,
    sitting: __sdk::TableUpdate<Sitting>,
    skill_cast: __sdk::TableUpdate<SkillCast>,
    skill_cooldown: __sdk::TableUpdate<SkillCooldownRow>,
    stats: __sdk::TableUpdate<Stats>,
    status_effect: __sdk::TableUpdate<StatusEffectRow>,
    store_item: __sdk::TableUpdate<StoreItem>,
    summon: __sdk::TableUpdate<Summon>,
    tick_stats: __sdk::TableUpdate<TickStats>,
    trade: __sdk::TableUpdate<Trade>,
    trade_request: __sdk::TableUpdate<TradeRequest>,
    world_rates: __sdk::TableUpdate<WorldRates>,
    xp_debt: __sdk::TableUpdate<XpDebt>,
    xp_event: __sdk::TableUpdate<XpEvent>,
    zone_info: __sdk::TableUpdate<ZoneInfo>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "bank" => db_update
                    .bank
                    .append(bank_table::parse_table_update(table_update)?),
                "combat" => db_update
                    .combat
                    .append(combat_table::parse_table_update(table_update)?),
                "damage_event" => db_update
                    .damage_event
                    .append(damage_event_table::parse_table_update(table_update)?),
                "driving" => db_update
                    .driving
                    .append(driving_table::parse_table_update(table_update)?),
                "entity" => db_update
                    .entity
                    .append(entity_table::parse_table_update(table_update)?),
                "fallen" => db_update
                    .fallen
                    .append(fallen_table::parse_table_update(table_update)?),
                "game_data_status" => db_update
                    .game_data_status
                    .append(game_data_status_table::parse_table_update(table_update)?),
                "ground_item" => db_update
                    .ground_item
                    .append(ground_item_table::parse_table_update(table_update)?),
                "motion" => db_update
                    .motion
                    .append(motion_table::parse_table_update(table_update)?),
                "my_chat" => db_update
                    .my_chat
                    .append(my_chat_table::parse_table_update(table_update)?),
                "my_friend_requests" => db_update
                    .my_friend_requests
                    .append(my_friend_requests_table::parse_table_update(table_update)?),
                "my_friends" => db_update
                    .my_friends
                    .append(my_friends_table::parse_table_update(table_update)?),
                "notice" => db_update
                    .notice
                    .append(notice_table::parse_table_update(table_update)?),
                "npc" => db_update
                    .npc
                    .append(npc_table::parse_table_update(table_update)?),
                "npc_cast_motion" => db_update
                    .npc_cast_motion
                    .append(npc_cast_motion_table::parse_table_update(table_update)?),
                "party" => db_update
                    .party
                    .append(party_table::parse_table_update(table_update)?),
                "party_invitation" => db_update
                    .party_invitation
                    .append(party_invitation_table::parse_table_update(table_update)?),
                "party_member" => db_update
                    .party_member
                    .append(party_member_table::parse_table_update(table_update)?),
                "personal_store" => db_update
                    .personal_store
                    .append(personal_store_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "revive_shield" => db_update
                    .revive_shield
                    .append(revive_shield_table::parse_table_update(table_update)?),
                "save_point" => db_update
                    .save_point
                    .append(save_point_table::parse_table_update(table_update)?),
                "sitting" => db_update
                    .sitting
                    .append(sitting_table::parse_table_update(table_update)?),
                "skill_cast" => db_update
                    .skill_cast
                    .append(skill_cast_table::parse_table_update(table_update)?),
                "skill_cooldown" => db_update
                    .skill_cooldown
                    .append(skill_cooldown_table::parse_table_update(table_update)?),
                "stats" => db_update
                    .stats
                    .append(stats_table::parse_table_update(table_update)?),
                "status_effect" => db_update
                    .status_effect
                    .append(status_effect_table::parse_table_update(table_update)?),
                "store_item" => db_update
                    .store_item
                    .append(store_item_table::parse_table_update(table_update)?),
                "summon" => db_update
                    .summon
                    .append(summon_table::parse_table_update(table_update)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(tick_stats_table::parse_table_update(table_update)?),
                "trade" => db_update
                    .trade
                    .append(trade_table::parse_table_update(table_update)?),
                "trade_request" => db_update
                    .trade_request
                    .append(trade_request_table::parse_table_update(table_update)?),
                "world_rates" => db_update
                    .world_rates
                    .append(world_rates_table::parse_table_update(table_update)?),
                "xp_debt" => db_update
                    .xp_debt
                    .append(xp_debt_table::parse_table_update(table_update)?),
                "xp_event" => db_update
                    .xp_event
                    .append(xp_event_table::parse_table_update(table_update)?),
                "zone_info" => db_update
                    .zone_info
                    .append(zone_info_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.bank = cache
            .apply_diff_to_table::<Bank>("bank", &self.bank)
            .with_updates_by_pk(|row| &row.identity);
        diff.combat = cache
            .apply_diff_to_table::<Combat>("combat", &self.combat)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.damage_event = self.damage_event.into_event_diff();
        diff.driving = cache
            .apply_diff_to_table::<Driving>("driving", &self.driving)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.entity = cache
            .apply_diff_to_table::<Entity>("entity", &self.entity)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.fallen = cache
            .apply_diff_to_table::<Fallen>("fallen", &self.fallen)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.game_data_status = cache
            .apply_diff_to_table::<GameDataStatus>("game_data_status", &self.game_data_status)
            .with_updates_by_pk(|row| &row.id);
        diff.ground_item = cache
            .apply_diff_to_table::<GroundItem>("ground_item", &self.ground_item)
            .with_updates_by_pk(|row| &row.drop_id);
        diff.motion = cache
            .apply_diff_to_table::<Motion>("motion", &self.motion)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.notice = self.notice.into_event_diff();
        diff.npc = cache
            .apply_diff_to_table::<Npc>("npc", &self.npc)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.npc_cast_motion = cache
            .apply_diff_to_table::<NpcCastMotion>("npc_cast_motion", &self.npc_cast_motion)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.party = cache
            .apply_diff_to_table::<Party>("party", &self.party)
            .with_updates_by_pk(|row| &row.party_id);
        diff.party_invitation = cache
            .apply_diff_to_table::<PartyInvite>("party_invitation", &self.party_invitation)
            .with_updates_by_pk(|row| &row.invite_id);
        diff.party_member = cache
            .apply_diff_to_table::<PartyMember>("party_member", &self.party_member)
            .with_updates_by_pk(|row| &row.identity);
        diff.personal_store = cache
            .apply_diff_to_table::<PersonalStore>("personal_store", &self.personal_store)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.identity);
        diff.revive_shield = cache
            .apply_diff_to_table::<ReviveShield>("revive_shield", &self.revive_shield)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.save_point = cache
            .apply_diff_to_table::<SavePoint>("save_point", &self.save_point)
            .with_updates_by_pk(|row| &row.identity);
        diff.sitting = cache
            .apply_diff_to_table::<Sitting>("sitting", &self.sitting)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.skill_cast = cache
            .apply_diff_to_table::<SkillCast>("skill_cast", &self.skill_cast)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.skill_cooldown = cache
            .apply_diff_to_table::<SkillCooldownRow>("skill_cooldown", &self.skill_cooldown)
            .with_updates_by_pk(|row| &row.id);
        diff.stats = cache
            .apply_diff_to_table::<Stats>("stats", &self.stats)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.status_effect = cache
            .apply_diff_to_table::<StatusEffectRow>("status_effect", &self.status_effect)
            .with_updates_by_pk(|row| &row.id);
        diff.store_item = cache
            .apply_diff_to_table::<StoreItem>("store_item", &self.store_item)
            .with_updates_by_pk(|row| &row.id);
        diff.summon = cache
            .apply_diff_to_table::<Summon>("summon", &self.summon)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.tick_stats = cache
            .apply_diff_to_table::<TickStats>("tick_stats", &self.tick_stats)
            .with_updates_by_pk(|row| &row.id);
        diff.trade = cache
            .apply_diff_to_table::<Trade>("trade", &self.trade)
            .with_updates_by_pk(|row| &row.trade_id);
        diff.trade_request = cache
            .apply_diff_to_table::<TradeRequest>("trade_request", &self.trade_request)
            .with_updates_by_pk(|row| &row.request_id);
        diff.world_rates = cache
            .apply_diff_to_table::<WorldRates>("world_rates", &self.world_rates)
            .with_updates_by_pk(|row| &row.id);
        diff.xp_debt = cache
            .apply_diff_to_table::<XpDebt>("xp_debt", &self.xp_debt)
            .with_updates_by_pk(|row| &row.identity);
        diff.xp_event = self.xp_event.into_event_diff();
        diff.zone_info = cache
            .apply_diff_to_table::<ZoneInfo>("zone_info", &self.zone_info)
            .with_updates_by_pk(|row| &row.zone_id);
        diff.my_chat = cache.apply_diff_to_table::<ChatMessage>("my_chat", &self.my_chat);
        diff.my_friend_requests = cache
            .apply_diff_to_table::<FriendRequest>("my_friend_requests", &self.my_friend_requests);
        diff.my_friends = cache.apply_diff_to_table::<FriendEntry>("my_friends", &self.my_friends);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "bank" => db_update
                    .bank
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "combat" => db_update
                    .combat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "damage_event" => db_update
                    .damage_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "driving" => db_update
                    .driving
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "entity" => db_update
                    .entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "fallen" => db_update
                    .fallen
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_data_status" => db_update
                    .game_data_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ground_item" => db_update
                    .ground_item
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "motion" => db_update
                    .motion
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_chat" => db_update
                    .my_chat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_friend_requests" => db_update
                    .my_friend_requests
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_friends" => db_update
                    .my_friends
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "notice" => db_update
                    .notice
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "npc" => db_update
                    .npc
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "npc_cast_motion" => db_update
                    .npc_cast_motion
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "party" => db_update
                    .party
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "party_invitation" => db_update
                    .party_invitation
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "party_member" => db_update
                    .party_member
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "personal_store" => db_update
                    .personal_store
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "revive_shield" => db_update
                    .revive_shield
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "save_point" => db_update
                    .save_point
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sitting" => db_update
                    .sitting
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "skill_cast" => db_update
                    .skill_cast
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "skill_cooldown" => db_update
                    .skill_cooldown
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "stats" => db_update
                    .stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "status_effect" => db_update
                    .status_effect
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "store_item" => db_update
                    .store_item
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "summon" => db_update
                    .summon
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "trade" => db_update
                    .trade
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "trade_request" => db_update
                    .trade_request
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world_rates" => db_update
                    .world_rates
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "xp_debt" => db_update
                    .xp_debt
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "xp_event" => db_update
                    .xp_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "zone_info" => db_update
                    .zone_info
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "bank" => db_update
                    .bank
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "combat" => db_update
                    .combat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "damage_event" => db_update
                    .damage_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "driving" => db_update
                    .driving
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "entity" => db_update
                    .entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "fallen" => db_update
                    .fallen
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_data_status" => db_update
                    .game_data_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ground_item" => db_update
                    .ground_item
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "motion" => db_update
                    .motion
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_chat" => db_update
                    .my_chat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_friend_requests" => db_update
                    .my_friend_requests
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_friends" => db_update
                    .my_friends
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "notice" => db_update
                    .notice
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "npc" => db_update
                    .npc
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "npc_cast_motion" => db_update
                    .npc_cast_motion
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "party" => db_update
                    .party
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "party_invitation" => db_update
                    .party_invitation
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "party_member" => db_update
                    .party_member
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "personal_store" => db_update
                    .personal_store
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "revive_shield" => db_update
                    .revive_shield
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "save_point" => db_update
                    .save_point
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sitting" => db_update
                    .sitting
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "skill_cast" => db_update
                    .skill_cast
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "skill_cooldown" => db_update
                    .skill_cooldown
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "stats" => db_update
                    .stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "status_effect" => db_update
                    .status_effect
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "store_item" => db_update
                    .store_item
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "summon" => db_update
                    .summon
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tick_stats" => db_update
                    .tick_stats
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "trade" => db_update
                    .trade
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "trade_request" => db_update
                    .trade_request
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world_rates" => db_update
                    .world_rates
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "xp_debt" => db_update
                    .xp_debt
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "xp_event" => db_update
                    .xp_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "zone_info" => db_update
                    .zone_info
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    bank: __sdk::TableAppliedDiff<'r, Bank>,
    combat: __sdk::TableAppliedDiff<'r, Combat>,
    damage_event: __sdk::TableAppliedDiff<'r, DamageEvent>,
    driving: __sdk::TableAppliedDiff<'r, Driving>,
    entity: __sdk::TableAppliedDiff<'r, Entity>,
    fallen: __sdk::TableAppliedDiff<'r, Fallen>,
    game_data_status: __sdk::TableAppliedDiff<'r, GameDataStatus>,
    ground_item: __sdk::TableAppliedDiff<'r, GroundItem>,
    motion: __sdk::TableAppliedDiff<'r, Motion>,
    my_chat: __sdk::TableAppliedDiff<'r, ChatMessage>,
    my_friend_requests: __sdk::TableAppliedDiff<'r, FriendRequest>,
    my_friends: __sdk::TableAppliedDiff<'r, FriendEntry>,
    notice: __sdk::TableAppliedDiff<'r, Notice>,
    npc: __sdk::TableAppliedDiff<'r, Npc>,
    npc_cast_motion: __sdk::TableAppliedDiff<'r, NpcCastMotion>,
    party: __sdk::TableAppliedDiff<'r, Party>,
    party_invitation: __sdk::TableAppliedDiff<'r, PartyInvite>,
    party_member: __sdk::TableAppliedDiff<'r, PartyMember>,
    personal_store: __sdk::TableAppliedDiff<'r, PersonalStore>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    revive_shield: __sdk::TableAppliedDiff<'r, ReviveShield>,
    save_point: __sdk::TableAppliedDiff<'r, SavePoint>,
    sitting: __sdk::TableAppliedDiff<'r, Sitting>,
    skill_cast: __sdk::TableAppliedDiff<'r, SkillCast>,
    skill_cooldown: __sdk::TableAppliedDiff<'r, SkillCooldownRow>,
    stats: __sdk::TableAppliedDiff<'r, Stats>,
    status_effect: __sdk::TableAppliedDiff<'r, StatusEffectRow>,
    store_item: __sdk::TableAppliedDiff<'r, StoreItem>,
    summon: __sdk::TableAppliedDiff<'r, Summon>,
    tick_stats: __sdk::TableAppliedDiff<'r, TickStats>,
    trade: __sdk::TableAppliedDiff<'r, Trade>,
    trade_request: __sdk::TableAppliedDiff<'r, TradeRequest>,
    world_rates: __sdk::TableAppliedDiff<'r, WorldRates>,
    xp_debt: __sdk::TableAppliedDiff<'r, XpDebt>,
    xp_event: __sdk::TableAppliedDiff<'r, XpEvent>,
    zone_info: __sdk::TableAppliedDiff<'r, ZoneInfo>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Bank>("bank", &self.bank, event);
        callbacks.invoke_table_row_callbacks::<Combat>("combat", &self.combat, event);
        callbacks.invoke_table_row_callbacks::<DamageEvent>(
            "damage_event",
            &self.damage_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Driving>("driving", &self.driving, event);
        callbacks.invoke_table_row_callbacks::<Entity>("entity", &self.entity, event);
        callbacks.invoke_table_row_callbacks::<Fallen>("fallen", &self.fallen, event);
        callbacks.invoke_table_row_callbacks::<GameDataStatus>(
            "game_data_status",
            &self.game_data_status,
            event,
        );
        callbacks.invoke_table_row_callbacks::<GroundItem>("ground_item", &self.ground_item, event);
        callbacks.invoke_table_row_callbacks::<Motion>("motion", &self.motion, event);
        callbacks.invoke_table_row_callbacks::<ChatMessage>("my_chat", &self.my_chat, event);
        callbacks.invoke_table_row_callbacks::<FriendRequest>(
            "my_friend_requests",
            &self.my_friend_requests,
            event,
        );
        callbacks.invoke_table_row_callbacks::<FriendEntry>("my_friends", &self.my_friends, event);
        callbacks.invoke_table_row_callbacks::<Notice>("notice", &self.notice, event);
        callbacks.invoke_table_row_callbacks::<Npc>("npc", &self.npc, event);
        callbacks.invoke_table_row_callbacks::<NpcCastMotion>(
            "npc_cast_motion",
            &self.npc_cast_motion,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Party>("party", &self.party, event);
        callbacks.invoke_table_row_callbacks::<PartyInvite>(
            "party_invitation",
            &self.party_invitation,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PartyMember>(
            "party_member",
            &self.party_member,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PersonalStore>(
            "personal_store",
            &self.personal_store,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<ReviveShield>(
            "revive_shield",
            &self.revive_shield,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SavePoint>("save_point", &self.save_point, event);
        callbacks.invoke_table_row_callbacks::<Sitting>("sitting", &self.sitting, event);
        callbacks.invoke_table_row_callbacks::<SkillCast>("skill_cast", &self.skill_cast, event);
        callbacks.invoke_table_row_callbacks::<SkillCooldownRow>(
            "skill_cooldown",
            &self.skill_cooldown,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Stats>("stats", &self.stats, event);
        callbacks.invoke_table_row_callbacks::<StatusEffectRow>(
            "status_effect",
            &self.status_effect,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StoreItem>("store_item", &self.store_item, event);
        callbacks.invoke_table_row_callbacks::<Summon>("summon", &self.summon, event);
        callbacks.invoke_table_row_callbacks::<TickStats>("tick_stats", &self.tick_stats, event);
        callbacks.invoke_table_row_callbacks::<Trade>("trade", &self.trade, event);
        callbacks.invoke_table_row_callbacks::<TradeRequest>(
            "trade_request",
            &self.trade_request,
            event,
        );
        callbacks.invoke_table_row_callbacks::<WorldRates>("world_rates", &self.world_rates, event);
        callbacks.invoke_table_row_callbacks::<XpDebt>("xp_debt", &self.xp_debt, event);
        callbacks.invoke_table_row_callbacks::<XpEvent>("xp_event", &self.xp_event, event);
        callbacks.invoke_table_row_callbacks::<ZoneInfo>("zone_info", &self.zone_info, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        bank_table::register_table(client_cache);
        combat_table::register_table(client_cache);
        damage_event_table::register_table(client_cache);
        driving_table::register_table(client_cache);
        entity_table::register_table(client_cache);
        fallen_table::register_table(client_cache);
        game_data_status_table::register_table(client_cache);
        ground_item_table::register_table(client_cache);
        motion_table::register_table(client_cache);
        my_chat_table::register_table(client_cache);
        my_friend_requests_table::register_table(client_cache);
        my_friends_table::register_table(client_cache);
        notice_table::register_table(client_cache);
        npc_table::register_table(client_cache);
        npc_cast_motion_table::register_table(client_cache);
        party_table::register_table(client_cache);
        party_invitation_table::register_table(client_cache);
        party_member_table::register_table(client_cache);
        personal_store_table::register_table(client_cache);
        player_table::register_table(client_cache);
        revive_shield_table::register_table(client_cache);
        save_point_table::register_table(client_cache);
        sitting_table::register_table(client_cache);
        skill_cast_table::register_table(client_cache);
        skill_cooldown_table::register_table(client_cache);
        stats_table::register_table(client_cache);
        status_effect_table::register_table(client_cache);
        store_item_table::register_table(client_cache);
        summon_table::register_table(client_cache);
        tick_stats_table::register_table(client_cache);
        trade_table::register_table(client_cache);
        trade_request_table::register_table(client_cache);
        world_rates_table::register_table(client_cache);
        xp_debt_table::register_table(client_cache);
        xp_event_table::register_table(client_cache);
        zone_info_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "bank",
        "combat",
        "damage_event",
        "driving",
        "entity",
        "fallen",
        "game_data_status",
        "ground_item",
        "motion",
        "my_chat",
        "my_friend_requests",
        "my_friends",
        "notice",
        "npc",
        "npc_cast_motion",
        "party",
        "party_invitation",
        "party_member",
        "personal_store",
        "player",
        "revive_shield",
        "save_point",
        "sitting",
        "skill_cast",
        "skill_cooldown",
        "stats",
        "status_effect",
        "store_item",
        "summon",
        "tick_stats",
        "trade",
        "trade_request",
        "world_rates",
        "xp_debt",
        "xp_event",
        "zone_info",
    ];
}
