// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::friend_entry_type::FriendEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_friends`.
///
/// Obtain a handle from the [`MyFriendsTableAccess::my_friends`] method on [`super::RemoteTables`],
/// like `ctx.db.my_friends()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_friends().on_insert(...)`.
pub struct MyFriendsTableHandle<'ctx> {
    imp: __sdk::TableHandle<FriendEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_friends`.
pub struct MyFriendsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyFriendsTableAccessor {
    type Row = FriendEntry;
    type Handle<'db> = MyFriendsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_friends()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_friends`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyFriendsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyFriendsTableHandle`], which mediates access to the table `my_friends`.
    fn my_friends(&self) -> MyFriendsTableHandle<'_>;
}

impl MyFriendsTableAccess for super::RemoteTables {
    fn my_friends(&self) -> MyFriendsTableHandle<'_> {
        MyFriendsTableHandle {
            imp: self.imp.get_table::<FriendEntry>("my_friends"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyFriendsInsertCallbackId(__sdk::CallbackId);
pub struct MyFriendsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyFriendsTableHandle<'ctx> {
    type Row = FriendEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FriendEntry> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyFriendsTableHandle<'ctx> {
    type Row = FriendEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FriendEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyFriendsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFriendsInsertCallbackId {
        MyFriendsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyFriendsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyFriendsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFriendsDeleteCallbackId {
        MyFriendsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyFriendsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyFriendsTableHandle<'ctx> {
    type InsertCallbackId = MyFriendsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFriendsInsertCallbackId {
        MyFriendsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyFriendsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyFriendsTableHandle<'ctx> {
    type DeleteCallbackId = MyFriendsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFriendsDeleteCallbackId {
        MyFriendsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyFriendsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FriendEntry>("my_friends");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FriendEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FriendEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FriendEntry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_friendsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FriendEntry`.
    fn my_friends(&self) -> __sdk::__query_builder::Table<FriendEntry>;
}

impl my_friendsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_friends(&self) -> __sdk::__query_builder::Table<FriendEntry> {
        __sdk::__query_builder::Table::new("my_friends")
    }
}
