// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PartySetRulesArgs {
    pub xp_sharing: u8,
    pub item_sharing: u8,
}

impl From<PartySetRulesArgs> for super::Reducer {
    fn from(args: PartySetRulesArgs) -> Self {
        Self::PartySetRules {
            xp_sharing: args.xp_sharing,
            item_sharing: args.item_sharing,
        }
    }
}

impl __sdk::InModule for PartySetRulesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `party_set_rules`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait party_set_rules {
    /// Request that the remote module invoke the reducer `party_set_rules` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`party_set_rules:party_set_rules_then`] to run a callback after the reducer completes.
    fn party_set_rules(&self, xp_sharing: u8, item_sharing: u8) -> __sdk::Result<()> {
        self.party_set_rules_then(xp_sharing, item_sharing, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `party_set_rules` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn party_set_rules_then(
        &self,
        xp_sharing: u8,
        item_sharing: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl party_set_rules for super::RemoteReducers {
    fn party_set_rules_then(
        &self,
        xp_sharing: u8,
        item_sharing: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PartySetRulesArgs {
                xp_sharing,
                item_sharing,
            },
            callback,
        )
    }
}
