// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::party_type::Party;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `party`.
///
/// Obtain a handle from the [`PartyTableAccess::party`] method on [`super::RemoteTables`],
/// like `ctx.db.party()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party().on_insert(...)`.
pub struct PartyTableHandle<'ctx> {
    imp: __sdk::TableHandle<Party>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `party`.
pub struct PartyTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PartyTableAccessor {
    type Row = Party;
    type Handle<'db> = PartyTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.party()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `party`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PartyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PartyTableHandle`], which mediates access to the table `party`.
    fn party(&self) -> PartyTableHandle<'_>;
}

impl PartyTableAccess for super::RemoteTables {
    fn party(&self) -> PartyTableHandle<'_> {
        PartyTableHandle {
            imp: self.imp.get_table::<Party>("party"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PartyInsertCallbackId(__sdk::CallbackId);
pub struct PartyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PartyTableHandle<'ctx> {
    type Row = Party;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Party> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PartyTableHandle<'ctx> {
    type Row = Party;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Party> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PartyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyInsertCallbackId {
        PartyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PartyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyDeleteCallbackId {
        PartyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PartyTableHandle<'ctx> {
    type InsertCallbackId = PartyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyInsertCallbackId {
        PartyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PartyTableHandle<'ctx> {
    type DeleteCallbackId = PartyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyDeleteCallbackId {
        PartyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PartyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PartyTableHandle<'ctx> {
    type UpdateCallbackId = PartyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyUpdateCallbackId {
        PartyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PartyTableHandle<'ctx> {
    type UpdateCallbackId = PartyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyUpdateCallbackId {
        PartyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `party_id` unique index on the table `party`,
/// which allows point queries on the field of the same name
/// via the [`PartyPartyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party().party_id().find(...)`.
pub struct PartyPartyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Party, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PartyTableHandle<'ctx> {
    /// Get a handle on the `party_id` unique index on the table `party`.
    pub fn party_id(&self) -> PartyPartyIdUnique<'ctx> {
        PartyPartyIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("party_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PartyPartyIdUnique<'ctx> {
    /// Find the subscribed row whose `party_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Party> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Party>("party");
    _table.add_unique_constraint::<u64>("party_id", |row| &row.party_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Party>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Party>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Party`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait partyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Party`.
    fn party(&self) -> __sdk::__query_builder::Table<Party>;
}

impl partyQueryTableAccess for __sdk::QueryTableAccessor {
    fn party(&self) -> __sdk::__query_builder::Table<Party> {
        __sdk::__query_builder::Table::new("party")
    }
}
