// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::party_invite_type::PartyInvite;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `party_invitation`.
///
/// Obtain a handle from the [`PartyInvitationTableAccess::party_invitation`] method on [`super::RemoteTables`],
/// like `ctx.db.party_invitation()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_invitation().on_insert(...)`.
pub struct PartyInvitationTableHandle<'ctx> {
    imp: __sdk::TableHandle<PartyInvite>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `party_invitation`.
pub struct PartyInvitationTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PartyInvitationTableAccessor {
    type Row = PartyInvite;
    type Handle<'db> = PartyInvitationTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.party_invitation()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `party_invitation`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PartyInvitationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PartyInvitationTableHandle`], which mediates access to the table `party_invitation`.
    fn party_invitation(&self) -> PartyInvitationTableHandle<'_>;
}

impl PartyInvitationTableAccess for super::RemoteTables {
    fn party_invitation(&self) -> PartyInvitationTableHandle<'_> {
        PartyInvitationTableHandle {
            imp: self.imp.get_table::<PartyInvite>("party_invitation"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PartyInvitationInsertCallbackId(__sdk::CallbackId);
pub struct PartyInvitationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PartyInvitationTableHandle<'ctx> {
    type Row = PartyInvite;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyInvite> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PartyInvitationTableHandle<'ctx> {
    type Row = PartyInvite;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyInvite> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PartyInvitationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyInvitationInsertCallbackId {
        PartyInvitationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyInvitationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PartyInvitationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyInvitationDeleteCallbackId {
        PartyInvitationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyInvitationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PartyInvitationTableHandle<'ctx> {
    type InsertCallbackId = PartyInvitationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyInvitationInsertCallbackId {
        PartyInvitationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyInvitationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PartyInvitationTableHandle<'ctx> {
    type DeleteCallbackId = PartyInvitationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyInvitationDeleteCallbackId {
        PartyInvitationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyInvitationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PartyInvitationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PartyInvitationTableHandle<'ctx> {
    type UpdateCallbackId = PartyInvitationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyInvitationUpdateCallbackId {
        PartyInvitationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyInvitationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PartyInvitationTableHandle<'ctx> {
    type UpdateCallbackId = PartyInvitationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyInvitationUpdateCallbackId {
        PartyInvitationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyInvitationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `invite_id` unique index on the table `party_invitation`,
/// which allows point queries on the field of the same name
/// via the [`PartyInvitationInviteIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_invitation().invite_id().find(...)`.
pub struct PartyInvitationInviteIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PartyInvite, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PartyInvitationTableHandle<'ctx> {
    /// Get a handle on the `invite_id` unique index on the table `party_invitation`.
    pub fn invite_id(&self) -> PartyInvitationInviteIdUnique<'ctx> {
        PartyInvitationInviteIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("invite_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PartyInvitationInviteIdUnique<'ctx> {
    /// Find the subscribed row whose `invite_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PartyInvite> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PartyInvite>("party_invitation");
    _table.add_unique_constraint::<u64>("invite_id", |row| &row.invite_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PartyInvite>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PartyInvite>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PartyInvite`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait party_invitationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PartyInvite`.
    fn party_invitation(&self) -> __sdk::__query_builder::Table<PartyInvite>;
}

impl party_invitationQueryTableAccess for __sdk::QueryTableAccessor {
    fn party_invitation(&self) -> __sdk::__query_builder::Table<PartyInvite> {
        __sdk::__query_builder::Table::new("party_invitation")
    }
}
