// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PartyAcceptArgs {
    pub invite_id: u64,
}

impl From<PartyAcceptArgs> for super::Reducer {
    fn from(args: PartyAcceptArgs) -> Self {
        Self::PartyAccept {
            invite_id: args.invite_id,
        }
    }
}

impl __sdk::InModule for PartyAcceptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `party_accept`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait party_accept {
    /// Request that the remote module invoke the reducer `party_accept` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`party_accept:party_accept_then`] to run a callback after the reducer completes.
    fn party_accept(&self, invite_id: u64) -> __sdk::Result<()> {
        self.party_accept_then(invite_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `party_accept` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn party_accept_then(
        &self,
        invite_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl party_accept for super::RemoteReducers {
    fn party_accept_then(
        &self,
        invite_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PartyAcceptArgs { invite_id }, callback)
    }
}
