// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Party {
    pub party_id: u64,
    pub owner: __sdk::Identity,
    pub xp_sharing: u8,
    pub item_sharing: u8,
    pub item_turn: u32,
    pub money_turn: u32,
}

impl __sdk::InModule for Party {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Party`.
///
/// Provides typed access to columns for query building.
pub struct PartyCols {
    pub party_id: __sdk::__query_builder::Col<Party, u64>,
    pub owner: __sdk::__query_builder::Col<Party, __sdk::Identity>,
    pub xp_sharing: __sdk::__query_builder::Col<Party, u8>,
    pub item_sharing: __sdk::__query_builder::Col<Party, u8>,
    pub item_turn: __sdk::__query_builder::Col<Party, u32>,
    pub money_turn: __sdk::__query_builder::Col<Party, u32>,
}

impl __sdk::__query_builder::HasCols for Party {
    type Cols = PartyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyCols {
            party_id: __sdk::__query_builder::Col::new(table_name, "party_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            xp_sharing: __sdk::__query_builder::Col::new(table_name, "xp_sharing"),
            item_sharing: __sdk::__query_builder::Col::new(table_name, "item_sharing"),
            item_turn: __sdk::__query_builder::Col::new(table_name, "item_turn"),
            money_turn: __sdk::__query_builder::Col::new(table_name, "money_turn"),
        }
    }
}

/// Indexed column accessor struct for the table `Party`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyIxCols {
    pub party_id: __sdk::__query_builder::IxCol<Party, u64>,
}

impl __sdk::__query_builder::HasIxCols for Party {
    type IxCols = PartyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyIxCols {
            party_id: __sdk::__query_builder::IxCol::new(table_name, "party_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Party {}
