// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PartyKickArgs {
    pub member: __sdk::Identity,
}

impl From<PartyKickArgs> for super::Reducer {
    fn from(args: PartyKickArgs) -> Self {
        Self::PartyKick {
            member: args.member,
        }
    }
}

impl __sdk::InModule for PartyKickArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `party_kick`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait party_kick {
    /// Request that the remote module invoke the reducer `party_kick` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`party_kick:party_kick_then`] to run a callback after the reducer completes.
    fn party_kick(&self, member: __sdk::Identity) -> __sdk::Result<()> {
        self.party_kick_then(member, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `party_kick` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn party_kick_then(
        &self,
        member: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl party_kick for super::RemoteReducers {
    fn party_kick_then(
        &self,
        member: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PartyKickArgs { member }, callback)
    }
}
