// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PartyInvite {
    pub invite_id: u64,
    pub from: __sdk::Identity,
    pub to: __sdk::Identity,
    pub expires_us: i64,
}

impl __sdk::InModule for PartyInvite {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PartyInvite`.
///
/// Provides typed access to columns for query building.
pub struct PartyInviteCols {
    pub invite_id: __sdk::__query_builder::Col<PartyInvite, u64>,
    pub from: __sdk::__query_builder::Col<PartyInvite, __sdk::Identity>,
    pub to: __sdk::__query_builder::Col<PartyInvite, __sdk::Identity>,
    pub expires_us: __sdk::__query_builder::Col<PartyInvite, i64>,
}

impl __sdk::__query_builder::HasCols for PartyInvite {
    type Cols = PartyInviteCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PartyInviteCols {
            invite_id: __sdk::__query_builder::Col::new(table_name, "invite_id"),
            from: __sdk::__query_builder::Col::new(table_name, "from"),
            to: __sdk::__query_builder::Col::new(table_name, "to"),
            expires_us: __sdk::__query_builder::Col::new(table_name, "expires_us"),
        }
    }
}

/// Indexed column accessor struct for the table `PartyInvite`.
///
/// Provides typed access to indexed columns for query building.
pub struct PartyInviteIxCols {
    pub invite_id: __sdk::__query_builder::IxCol<PartyInvite, u64>,
    pub to: __sdk::__query_builder::IxCol<PartyInvite, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PartyInvite {
    type IxCols = PartyInviteIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PartyInviteIxCols {
            invite_id: __sdk::__query_builder::IxCol::new(table_name, "invite_id"),
            to: __sdk::__query_builder::IxCol::new(table_name, "to"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PartyInvite {}
