// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::party_member_type::PartyMember;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `party_member`.
///
/// Obtain a handle from the [`PartyMemberTableAccess::party_member`] method on [`super::RemoteTables`],
/// like `ctx.db.party_member()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_member().on_insert(...)`.
pub struct PartyMemberTableHandle<'ctx> {
    imp: __sdk::TableHandle<PartyMember>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `party_member`.
pub struct PartyMemberTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PartyMemberTableAccessor {
    type Row = PartyMember;
    type Handle<'db> = PartyMemberTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.party_member()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `party_member`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PartyMemberTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PartyMemberTableHandle`], which mediates access to the table `party_member`.
    fn party_member(&self) -> PartyMemberTableHandle<'_>;
}

impl PartyMemberTableAccess for super::RemoteTables {
    fn party_member(&self) -> PartyMemberTableHandle<'_> {
        PartyMemberTableHandle {
            imp: self.imp.get_table::<PartyMember>("party_member"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PartyMemberInsertCallbackId(__sdk::CallbackId);
pub struct PartyMemberDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PartyMemberTableHandle<'ctx> {
    type Row = PartyMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyMember> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PartyMemberTableHandle<'ctx> {
    type Row = PartyMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PartyMember> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PartyMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyMemberInsertCallbackId {
        PartyMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PartyMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyMemberDeleteCallbackId {
        PartyMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PartyMemberTableHandle<'ctx> {
    type InsertCallbackId = PartyMemberInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyMemberInsertCallbackId {
        PartyMemberInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PartyMemberInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PartyMemberTableHandle<'ctx> {
    type DeleteCallbackId = PartyMemberDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PartyMemberDeleteCallbackId {
        PartyMemberDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PartyMemberDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PartyMemberUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PartyMemberTableHandle<'ctx> {
    type UpdateCallbackId = PartyMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyMemberUpdateCallbackId {
        PartyMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PartyMemberTableHandle<'ctx> {
    type UpdateCallbackId = PartyMemberUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PartyMemberUpdateCallbackId {
        PartyMemberUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PartyMemberUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `party_member`,
/// which allows point queries on the field of the same name
/// via the [`PartyMemberIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.party_member().identity().find(...)`.
pub struct PartyMemberIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PartyMember, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PartyMemberTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `party_member`.
    pub fn identity(&self) -> PartyMemberIdentityUnique<'ctx> {
        PartyMemberIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PartyMemberIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PartyMember> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PartyMember>("party_member");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PartyMember>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PartyMember>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PartyMember`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait party_memberQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PartyMember`.
    fn party_member(&self) -> __sdk::__query_builder::Table<PartyMember>;
}

impl party_memberQueryTableAccess for __sdk::QueryTableAccessor {
    fn party_member(&self) -> __sdk::__query_builder::Table<PartyMember> {
        __sdk::__query_builder::Table::new("party_member")
    }
}
