// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Passenger {
    pub guest: u64,
    pub driver: u64,
    pub since_us: i64,
}

impl __sdk::InModule for Passenger {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Passenger`.
///
/// Provides typed access to columns for query building.
pub struct PassengerCols {
    pub guest: __sdk::__query_builder::Col<Passenger, u64>,
    pub driver: __sdk::__query_builder::Col<Passenger, u64>,
    pub since_us: __sdk::__query_builder::Col<Passenger, i64>,
}

impl __sdk::__query_builder::HasCols for Passenger {
    type Cols = PassengerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PassengerCols {
            guest: __sdk::__query_builder::Col::new(table_name, "guest"),
            driver: __sdk::__query_builder::Col::new(table_name, "driver"),
            since_us: __sdk::__query_builder::Col::new(table_name, "since_us"),
        }
    }
}

/// Indexed column accessor struct for the table `Passenger`.
///
/// Provides typed access to indexed columns for query building.
pub struct PassengerIxCols {
    pub driver: __sdk::__query_builder::IxCol<Passenger, u64>,
    pub guest: __sdk::__query_builder::IxCol<Passenger, u64>,
}

impl __sdk::__query_builder::HasIxCols for Passenger {
    type IxCols = PassengerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PassengerIxCols {
            driver: __sdk::__query_builder::IxCol::new(table_name, "driver"),
            guest: __sdk::__query_builder::IxCol::new(table_name, "guest"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Passenger {}
