// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PersonalStore {
    pub entity_id: u64,
    pub owner: __sdk::Identity,
    pub title: String,
    pub opened_at_us: i64,
}

impl __sdk::InModule for PersonalStore {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PersonalStore`.
///
/// Provides typed access to columns for query building.
pub struct PersonalStoreCols {
    pub entity_id: __sdk::__query_builder::Col<PersonalStore, u64>,
    pub owner: __sdk::__query_builder::Col<PersonalStore, __sdk::Identity>,
    pub title: __sdk::__query_builder::Col<PersonalStore, String>,
    pub opened_at_us: __sdk::__query_builder::Col<PersonalStore, i64>,
}

impl __sdk::__query_builder::HasCols for PersonalStore {
    type Cols = PersonalStoreCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PersonalStoreCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            opened_at_us: __sdk::__query_builder::Col::new(table_name, "opened_at_us"),
        }
    }
}

/// Indexed column accessor struct for the table `PersonalStore`.
///
/// Provides typed access to indexed columns for query building.
pub struct PersonalStoreIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PersonalStore, u64>,
    pub owner: __sdk::__query_builder::IxCol<PersonalStore, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PersonalStore {
    type IxCols = PersonalStoreIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PersonalStoreIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PersonalStore {}
