// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlacePlayerArgs {
    pub name: String,
    pub x: f32,
    pub y: f32,
}

impl From<PlacePlayerArgs> for super::Reducer {
    fn from(args: PlacePlayerArgs) -> Self {
        Self::PlacePlayer {
            name: args.name,
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for PlacePlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_player {
    /// Request that the remote module invoke the reducer `place_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_player:place_player_then`] to run a callback after the reducer completes.
    fn place_player(&self, name: String, x: f32, y: f32) -> __sdk::Result<()> {
        self.place_player_then(name, x, y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_player_then(
        &self,
        name: String,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_player for super::RemoteReducers {
    fn place_player_then(
        &self,
        name: String,
        x: f32,
        y: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PlacePlayerArgs { name, x, y }, callback)
    }
}
