// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub identity: __sdk::Identity,
    pub entity_id: Option<u64>,
    pub name: String,
    pub online: bool,
    pub zone_id: u16,
    pub last_x: f32,
    pub last_y: f32,
    pub last_hp: i32,
    pub last_mp: i32,
    pub gender: u8,
    pub face: u8,
    pub hair: u8,
    pub job: u16,
    pub level: u32,
    pub xp: u64,
    pub stat_points: u32,
    pub skill_points: u32,
    pub money: i64,
    pub strength: i32,
    pub dexterity: i32,
    pub intelligence: i32,
    pub concentration: i32,
    pub charm: i32,
    pub sense: i32,
    pub equipment: String,
    pub inventory: String,
    pub skill_list: String,
    pub quest_state: String,
    pub hotbar: String,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub identity: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub entity_id: __sdk::__query_builder::Col<Player, Option<u64>>,
    pub name: __sdk::__query_builder::Col<Player, String>,
    pub online: __sdk::__query_builder::Col<Player, bool>,
    pub zone_id: __sdk::__query_builder::Col<Player, u16>,
    pub last_x: __sdk::__query_builder::Col<Player, f32>,
    pub last_y: __sdk::__query_builder::Col<Player, f32>,
    pub last_hp: __sdk::__query_builder::Col<Player, i32>,
    pub last_mp: __sdk::__query_builder::Col<Player, i32>,
    pub gender: __sdk::__query_builder::Col<Player, u8>,
    pub face: __sdk::__query_builder::Col<Player, u8>,
    pub hair: __sdk::__query_builder::Col<Player, u8>,
    pub job: __sdk::__query_builder::Col<Player, u16>,
    pub level: __sdk::__query_builder::Col<Player, u32>,
    pub xp: __sdk::__query_builder::Col<Player, u64>,
    pub stat_points: __sdk::__query_builder::Col<Player, u32>,
    pub skill_points: __sdk::__query_builder::Col<Player, u32>,
    pub money: __sdk::__query_builder::Col<Player, i64>,
    pub strength: __sdk::__query_builder::Col<Player, i32>,
    pub dexterity: __sdk::__query_builder::Col<Player, i32>,
    pub intelligence: __sdk::__query_builder::Col<Player, i32>,
    pub concentration: __sdk::__query_builder::Col<Player, i32>,
    pub charm: __sdk::__query_builder::Col<Player, i32>,
    pub sense: __sdk::__query_builder::Col<Player, i32>,
    pub equipment: __sdk::__query_builder::Col<Player, String>,
    pub inventory: __sdk::__query_builder::Col<Player, String>,
    pub skill_list: __sdk::__query_builder::Col<Player, String>,
    pub quest_state: __sdk::__query_builder::Col<Player, String>,
    pub hotbar: __sdk::__query_builder::Col<Player, String>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            online: __sdk::__query_builder::Col::new(table_name, "online"),
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            last_x: __sdk::__query_builder::Col::new(table_name, "last_x"),
            last_y: __sdk::__query_builder::Col::new(table_name, "last_y"),
            last_hp: __sdk::__query_builder::Col::new(table_name, "last_hp"),
            last_mp: __sdk::__query_builder::Col::new(table_name, "last_mp"),
            gender: __sdk::__query_builder::Col::new(table_name, "gender"),
            face: __sdk::__query_builder::Col::new(table_name, "face"),
            hair: __sdk::__query_builder::Col::new(table_name, "hair"),
            job: __sdk::__query_builder::Col::new(table_name, "job"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            xp: __sdk::__query_builder::Col::new(table_name, "xp"),
            stat_points: __sdk::__query_builder::Col::new(table_name, "stat_points"),
            skill_points: __sdk::__query_builder::Col::new(table_name, "skill_points"),
            money: __sdk::__query_builder::Col::new(table_name, "money"),
            strength: __sdk::__query_builder::Col::new(table_name, "strength"),
            dexterity: __sdk::__query_builder::Col::new(table_name, "dexterity"),
            intelligence: __sdk::__query_builder::Col::new(table_name, "intelligence"),
            concentration: __sdk::__query_builder::Col::new(table_name, "concentration"),
            charm: __sdk::__query_builder::Col::new(table_name, "charm"),
            sense: __sdk::__query_builder::Col::new(table_name, "sense"),
            equipment: __sdk::__query_builder::Col::new(table_name, "equipment"),
            inventory: __sdk::__query_builder::Col::new(table_name, "inventory"),
            skill_list: __sdk::__query_builder::Col::new(table_name, "skill_list"),
            quest_state: __sdk::__query_builder::Col::new(table_name, "quest_state"),
            hotbar: __sdk::__query_builder::Col::new(table_name, "hotbar"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub identity: __sdk::__query_builder::IxCol<Player, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
