// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::revive_shield_type::ReviveShield;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `revive_shield`.
///
/// Obtain a handle from the [`ReviveShieldTableAccess::revive_shield`] method on [`super::RemoteTables`],
/// like `ctx.db.revive_shield()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.revive_shield().on_insert(...)`.
pub struct ReviveShieldTableHandle<'ctx> {
    imp: __sdk::TableHandle<ReviveShield>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `revive_shield`.
pub struct ReviveShieldTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ReviveShieldTableAccessor {
    type Row = ReviveShield;
    type Handle<'db> = ReviveShieldTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.revive_shield()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `revive_shield`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ReviveShieldTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ReviveShieldTableHandle`], which mediates access to the table `revive_shield`.
    fn revive_shield(&self) -> ReviveShieldTableHandle<'_>;
}

impl ReviveShieldTableAccess for super::RemoteTables {
    fn revive_shield(&self) -> ReviveShieldTableHandle<'_> {
        ReviveShieldTableHandle {
            imp: self.imp.get_table::<ReviveShield>("revive_shield"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ReviveShieldInsertCallbackId(__sdk::CallbackId);
pub struct ReviveShieldDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ReviveShieldTableHandle<'ctx> {
    type Row = ReviveShield;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ReviveShield> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ReviveShieldTableHandle<'ctx> {
    type Row = ReviveShield;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ReviveShield> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ReviveShieldInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReviveShieldInsertCallbackId {
        ReviveShieldInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ReviveShieldInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ReviveShieldDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReviveShieldDeleteCallbackId {
        ReviveShieldDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ReviveShieldDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ReviveShieldTableHandle<'ctx> {
    type InsertCallbackId = ReviveShieldInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReviveShieldInsertCallbackId {
        ReviveShieldInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ReviveShieldInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ReviveShieldTableHandle<'ctx> {
    type DeleteCallbackId = ReviveShieldDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ReviveShieldDeleteCallbackId {
        ReviveShieldDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ReviveShieldDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ReviveShieldUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ReviveShieldTableHandle<'ctx> {
    type UpdateCallbackId = ReviveShieldUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ReviveShieldUpdateCallbackId {
        ReviveShieldUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ReviveShieldUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ReviveShieldTableHandle<'ctx> {
    type UpdateCallbackId = ReviveShieldUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ReviveShieldUpdateCallbackId {
        ReviveShieldUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ReviveShieldUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `revive_shield`,
/// which allows point queries on the field of the same name
/// via the [`ReviveShieldEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.revive_shield().entity_id().find(...)`.
pub struct ReviveShieldEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ReviveShield, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ReviveShieldTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `revive_shield`.
    pub fn entity_id(&self) -> ReviveShieldEntityIdUnique<'ctx> {
        ReviveShieldEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ReviveShieldEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ReviveShield> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ReviveShield>("revive_shield");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ReviveShield>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ReviveShield>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ReviveShield`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait revive_shieldQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ReviveShield`.
    fn revive_shield(&self) -> __sdk::__query_builder::Table<ReviveShield>;
}

impl revive_shieldQueryTableAccess for __sdk::QueryTableAccessor {
    fn revive_shield(&self) -> __sdk::__query_builder::Table<ReviveShield> {
        __sdk::__query_builder::Table::new("revive_shield")
    }
}
