// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RideAnswerArgs {
    pub offer_id: u64,
    pub accept: bool,
}

impl From<RideAnswerArgs> for super::Reducer {
    fn from(args: RideAnswerArgs) -> Self {
        Self::RideAnswer {
            offer_id: args.offer_id,
            accept: args.accept,
        }
    }
}

impl __sdk::InModule for RideAnswerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ride_answer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ride_answer {
    /// Request that the remote module invoke the reducer `ride_answer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ride_answer:ride_answer_then`] to run a callback after the reducer completes.
    fn ride_answer(&self, offer_id: u64, accept: bool) -> __sdk::Result<()> {
        self.ride_answer_then(offer_id, accept, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ride_answer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ride_answer_then(
        &self,
        offer_id: u64,
        accept: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ride_answer for super::RemoteReducers {
    fn ride_answer_then(
        &self,
        offer_id: u64,
        accept: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RideAnswerArgs { offer_id, accept }, callback)
    }
}
