// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::save_point_type::SavePoint;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `save_point`.
///
/// Obtain a handle from the [`SavePointTableAccess::save_point`] method on [`super::RemoteTables`],
/// like `ctx.db.save_point()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.save_point().on_insert(...)`.
pub struct SavePointTableHandle<'ctx> {
    imp: __sdk::TableHandle<SavePoint>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `save_point`.
pub struct SavePointTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SavePointTableAccessor {
    type Row = SavePoint;
    type Handle<'db> = SavePointTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.save_point()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `save_point`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SavePointTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SavePointTableHandle`], which mediates access to the table `save_point`.
    fn save_point(&self) -> SavePointTableHandle<'_>;
}

impl SavePointTableAccess for super::RemoteTables {
    fn save_point(&self) -> SavePointTableHandle<'_> {
        SavePointTableHandle {
            imp: self.imp.get_table::<SavePoint>("save_point"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SavePointInsertCallbackId(__sdk::CallbackId);
pub struct SavePointDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SavePointTableHandle<'ctx> {
    type Row = SavePoint;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SavePoint> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SavePointTableHandle<'ctx> {
    type Row = SavePoint;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SavePoint> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SavePointInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SavePointInsertCallbackId {
        SavePointInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SavePointInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SavePointDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SavePointDeleteCallbackId {
        SavePointDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SavePointDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SavePointTableHandle<'ctx> {
    type InsertCallbackId = SavePointInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SavePointInsertCallbackId {
        SavePointInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SavePointInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SavePointTableHandle<'ctx> {
    type DeleteCallbackId = SavePointDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SavePointDeleteCallbackId {
        SavePointDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SavePointDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SavePointUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SavePointTableHandle<'ctx> {
    type UpdateCallbackId = SavePointUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SavePointUpdateCallbackId {
        SavePointUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SavePointUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SavePointTableHandle<'ctx> {
    type UpdateCallbackId = SavePointUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SavePointUpdateCallbackId {
        SavePointUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SavePointUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `save_point`,
/// which allows point queries on the field of the same name
/// via the [`SavePointIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.save_point().identity().find(...)`.
pub struct SavePointIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SavePoint, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SavePointTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `save_point`.
    pub fn identity(&self) -> SavePointIdentityUnique<'ctx> {
        SavePointIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SavePointIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<SavePoint> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SavePoint>("save_point");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SavePoint>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SavePoint>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SavePoint`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait save_pointQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SavePoint`.
    fn save_point(&self) -> __sdk::__query_builder::Table<SavePoint>;
}

impl save_pointQueryTableAccess for __sdk::QueryTableAccessor {
    fn save_point(&self) -> __sdk::__query_builder::Table<SavePoint> {
        __sdk::__query_builder::Table::new("save_point")
    }
}
