// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetNpcVariableArgs {
    pub npc_id: u16,
    pub variable_id: u8,
    pub value: i32,
}

impl From<SetNpcVariableArgs> for super::Reducer {
    fn from(args: SetNpcVariableArgs) -> Self {
        Self::SetNpcVariable {
            npc_id: args.npc_id,
            variable_id: args.variable_id,
            value: args.value,
        }
    }
}

impl __sdk::InModule for SetNpcVariableArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_npc_variable`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_npc_variable {
    /// Request that the remote module invoke the reducer `set_npc_variable` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_npc_variable:set_npc_variable_then`] to run a callback after the reducer completes.
    fn set_npc_variable(&self, npc_id: u16, variable_id: u8, value: i32) -> __sdk::Result<()> {
        self.set_npc_variable_then(npc_id, variable_id, value, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_npc_variable` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_npc_variable_then(
        &self,
        npc_id: u16,
        variable_id: u8,
        value: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_npc_variable for super::RemoteReducers {
    fn set_npc_variable_then(
        &self,
        npc_id: u16,
        variable_id: u8,
        value: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetNpcVariableArgs {
                npc_id,
                variable_id,
                value,
            },
            callback,
        )
    }
}
