// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetWorldRatesArgs {
    pub xp_rate: i32,
    pub drop_rate: i32,
    pub drop_money_rate: i32,
    pub reward_rate: i32,
}

impl From<SetWorldRatesArgs> for super::Reducer {
    fn from(args: SetWorldRatesArgs) -> Self {
        Self::SetWorldRates {
            xp_rate: args.xp_rate,
            drop_rate: args.drop_rate,
            drop_money_rate: args.drop_money_rate,
            reward_rate: args.reward_rate,
        }
    }
}

impl __sdk::InModule for SetWorldRatesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_world_rates`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_world_rates {
    /// Request that the remote module invoke the reducer `set_world_rates` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_world_rates:set_world_rates_then`] to run a callback after the reducer completes.
    fn set_world_rates(
        &self,
        xp_rate: i32,
        drop_rate: i32,
        drop_money_rate: i32,
        reward_rate: i32,
    ) -> __sdk::Result<()> {
        self.set_world_rates_then(xp_rate, drop_rate, drop_money_rate, reward_rate, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_world_rates` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_world_rates_then(
        &self,
        xp_rate: i32,
        drop_rate: i32,
        drop_money_rate: i32,
        reward_rate: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_world_rates for super::RemoteReducers {
    fn set_world_rates_then(
        &self,
        xp_rate: i32,
        drop_rate: i32,
        drop_money_rate: i32,
        reward_rate: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetWorldRatesArgs {
                xp_rate,
                drop_rate,
                drop_money_rate,
                reward_rate,
            },
            callback,
        )
    }
}
