// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetAggroRangeArgs {
    pub npc_id: u16,
    pub range: f32,
}

impl From<SetAggroRangeArgs> for super::Reducer {
    fn from(args: SetAggroRangeArgs) -> Self {
        Self::SetAggroRange {
            npc_id: args.npc_id,
            range: args.range,
        }
    }
}

impl __sdk::InModule for SetAggroRangeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_aggro_range`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_aggro_range {
    /// Request that the remote module invoke the reducer `set_aggro_range` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_aggro_range:set_aggro_range_then`] to run a callback after the reducer completes.
    fn set_aggro_range(&self, npc_id: u16, range: f32) -> __sdk::Result<()> {
        self.set_aggro_range_then(npc_id, range, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_aggro_range` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_aggro_range_then(
        &self,
        npc_id: u16,
        range: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_aggro_range for super::RemoteReducers {
    fn set_aggro_range_then(
        &self,
        npc_id: u16,
        range: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetAggroRangeArgs { npc_id, range }, callback)
    }
}
