// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::skill_cooldown_row_type::SkillCooldownRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `skill_cooldown`.
///
/// Obtain a handle from the [`SkillCooldownTableAccess::skill_cooldown`] method on [`super::RemoteTables`],
/// like `ctx.db.skill_cooldown()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_cooldown().on_insert(...)`.
pub struct SkillCooldownTableHandle<'ctx> {
    imp: __sdk::TableHandle<SkillCooldownRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `skill_cooldown`.
pub struct SkillCooldownTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SkillCooldownTableAccessor {
    type Row = SkillCooldownRow;
    type Handle<'db> = SkillCooldownTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.skill_cooldown()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `skill_cooldown`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SkillCooldownTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SkillCooldownTableHandle`], which mediates access to the table `skill_cooldown`.
    fn skill_cooldown(&self) -> SkillCooldownTableHandle<'_>;
}

impl SkillCooldownTableAccess for super::RemoteTables {
    fn skill_cooldown(&self) -> SkillCooldownTableHandle<'_> {
        SkillCooldownTableHandle {
            imp: self.imp.get_table::<SkillCooldownRow>("skill_cooldown"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SkillCooldownInsertCallbackId(__sdk::CallbackId);
pub struct SkillCooldownDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SkillCooldownTableHandle<'ctx> {
    type Row = SkillCooldownRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SkillCooldownRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SkillCooldownTableHandle<'ctx> {
    type Row = SkillCooldownRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SkillCooldownRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SkillCooldownInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillCooldownInsertCallbackId {
        SkillCooldownInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillCooldownInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SkillCooldownDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillCooldownDeleteCallbackId {
        SkillCooldownDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillCooldownDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SkillCooldownTableHandle<'ctx> {
    type InsertCallbackId = SkillCooldownInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillCooldownInsertCallbackId {
        SkillCooldownInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillCooldownInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SkillCooldownTableHandle<'ctx> {
    type DeleteCallbackId = SkillCooldownDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillCooldownDeleteCallbackId {
        SkillCooldownDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillCooldownDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SkillCooldownUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SkillCooldownTableHandle<'ctx> {
    type UpdateCallbackId = SkillCooldownUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillCooldownUpdateCallbackId {
        SkillCooldownUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillCooldownUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SkillCooldownTableHandle<'ctx> {
    type UpdateCallbackId = SkillCooldownUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillCooldownUpdateCallbackId {
        SkillCooldownUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillCooldownUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `skill_cooldown`,
/// which allows point queries on the field of the same name
/// via the [`SkillCooldownIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_cooldown().id().find(...)`.
pub struct SkillCooldownIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SkillCooldownRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SkillCooldownTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `skill_cooldown`.
    pub fn id(&self) -> SkillCooldownIdUnique<'ctx> {
        SkillCooldownIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SkillCooldownIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SkillCooldownRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SkillCooldownRow>("skill_cooldown");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SkillCooldownRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SkillCooldownRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SkillCooldownRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait skill_cooldownQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SkillCooldownRow`.
    fn skill_cooldown(&self) -> __sdk::__query_builder::Table<SkillCooldownRow>;
}

impl skill_cooldownQueryTableAccess for __sdk::QueryTableAccessor {
    fn skill_cooldown(&self) -> __sdk::__query_builder::Table<SkillCooldownRow> {
        __sdk::__query_builder::Table::new("skill_cooldown")
    }
}
