// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpawnTickTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for SpawnTickTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpawnTickTimer`.
///
/// Provides typed access to columns for query building.
pub struct SpawnTickTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<SpawnTickTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<SpawnTickTimer, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for SpawnTickTimer {
    type Cols = SpawnTickTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpawnTickTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SpawnTickTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpawnTickTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<SpawnTickTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for SpawnTickTimer {
    type IxCols = SpawnTickTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpawnTickTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpawnTickTimer {}
