// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stats_type::Stats;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stats`.
///
/// Obtain a handle from the [`StatsTableAccess::stats`] method on [`super::RemoteTables`],
/// like `ctx.db.stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stats().on_insert(...)`.
pub struct StatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Stats>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `stats`.
pub struct StatsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for StatsTableAccessor {
    type Row = Stats;
    type Handle<'db> = StatsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.stats()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StatsTableHandle`], which mediates access to the table `stats`.
    fn stats(&self) -> StatsTableHandle<'_>;
}

impl StatsTableAccess for super::RemoteTables {
    fn stats(&self) -> StatsTableHandle<'_> {
        StatsTableHandle {
            imp: self.imp.get_table::<Stats>("stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StatsInsertCallbackId(__sdk::CallbackId);
pub struct StatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for StatsTableHandle<'ctx> {
    type Row = Stats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Stats> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for StatsTableHandle<'ctx> {
    type Row = Stats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Stats> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatsInsertCallbackId {
        StatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatsDeleteCallbackId {
        StatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for StatsTableHandle<'ctx> {
    type InsertCallbackId = StatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatsInsertCallbackId {
        StatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for StatsTableHandle<'ctx> {
    type DeleteCallbackId = StatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatsDeleteCallbackId {
        StatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StatsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StatsTableHandle<'ctx> {
    type UpdateCallbackId = StatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StatsUpdateCallbackId {
        StatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for StatsTableHandle<'ctx> {
    type UpdateCallbackId = StatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StatsUpdateCallbackId {
        StatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `stats`,
/// which allows point queries on the field of the same name
/// via the [`StatsEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stats().entity_id().find(...)`.
pub struct StatsEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Stats, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StatsTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `stats`.
    pub fn entity_id(&self) -> StatsEntityIdUnique<'ctx> {
        StatsEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StatsEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Stats> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Stats>("stats");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Stats>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Stats>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Stats`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait statsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Stats`.
    fn stats(&self) -> __sdk::__query_builder::Table<Stats>;
}

impl statsQueryTableAccess for __sdk::QueryTableAccessor {
    fn stats(&self) -> __sdk::__query_builder::Table<Stats> {
        __sdk::__query_builder::Table::new("stats")
    }
}
