// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StatusEffectRow {
    pub id: u64,
    pub entity_id: u64,
    pub effect_type: u8,
    pub status_effect_id: u16,
    pub value: i32,
    pub expires_at_us: i64,
}

impl __sdk::InModule for StatusEffectRow {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StatusEffectRow`.
///
/// Provides typed access to columns for query building.
pub struct StatusEffectRowCols {
    pub id: __sdk::__query_builder::Col<StatusEffectRow, u64>,
    pub entity_id: __sdk::__query_builder::Col<StatusEffectRow, u64>,
    pub effect_type: __sdk::__query_builder::Col<StatusEffectRow, u8>,
    pub status_effect_id: __sdk::__query_builder::Col<StatusEffectRow, u16>,
    pub value: __sdk::__query_builder::Col<StatusEffectRow, i32>,
    pub expires_at_us: __sdk::__query_builder::Col<StatusEffectRow, i64>,
}

impl __sdk::__query_builder::HasCols for StatusEffectRow {
    type Cols = StatusEffectRowCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StatusEffectRowCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            effect_type: __sdk::__query_builder::Col::new(table_name, "effect_type"),
            status_effect_id: __sdk::__query_builder::Col::new(table_name, "status_effect_id"),
            value: __sdk::__query_builder::Col::new(table_name, "value"),
            expires_at_us: __sdk::__query_builder::Col::new(table_name, "expires_at_us"),
        }
    }
}

/// Indexed column accessor struct for the table `StatusEffectRow`.
///
/// Provides typed access to indexed columns for query building.
pub struct StatusEffectRowIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<StatusEffectRow, u64>,
    pub id: __sdk::__query_builder::IxCol<StatusEffectRow, u64>,
}

impl __sdk::__query_builder::HasIxCols for StatusEffectRow {
    type IxCols = StatusEffectRowIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StatusEffectRowIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StatusEffectRow {}
