// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::status_effect_row_type::StatusEffectRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `status_effect`.
///
/// Obtain a handle from the [`StatusEffectTableAccess::status_effect`] method on [`super::RemoteTables`],
/// like `ctx.db.status_effect()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.status_effect().on_insert(...)`.
pub struct StatusEffectTableHandle<'ctx> {
    imp: __sdk::TableHandle<StatusEffectRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `status_effect`.
pub struct StatusEffectTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for StatusEffectTableAccessor {
    type Row = StatusEffectRow;
    type Handle<'db> = StatusEffectTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.status_effect()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `status_effect`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StatusEffectTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StatusEffectTableHandle`], which mediates access to the table `status_effect`.
    fn status_effect(&self) -> StatusEffectTableHandle<'_>;
}

impl StatusEffectTableAccess for super::RemoteTables {
    fn status_effect(&self) -> StatusEffectTableHandle<'_> {
        StatusEffectTableHandle {
            imp: self.imp.get_table::<StatusEffectRow>("status_effect"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StatusEffectInsertCallbackId(__sdk::CallbackId);
pub struct StatusEffectDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for StatusEffectTableHandle<'ctx> {
    type Row = StatusEffectRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StatusEffectRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for StatusEffectTableHandle<'ctx> {
    type Row = StatusEffectRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StatusEffectRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StatusEffectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatusEffectInsertCallbackId {
        StatusEffectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StatusEffectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StatusEffectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatusEffectDeleteCallbackId {
        StatusEffectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StatusEffectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for StatusEffectTableHandle<'ctx> {
    type InsertCallbackId = StatusEffectInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatusEffectInsertCallbackId {
        StatusEffectInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StatusEffectInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for StatusEffectTableHandle<'ctx> {
    type DeleteCallbackId = StatusEffectDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatusEffectDeleteCallbackId {
        StatusEffectDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StatusEffectDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StatusEffectUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StatusEffectTableHandle<'ctx> {
    type UpdateCallbackId = StatusEffectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StatusEffectUpdateCallbackId {
        StatusEffectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StatusEffectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for StatusEffectTableHandle<'ctx> {
    type UpdateCallbackId = StatusEffectUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StatusEffectUpdateCallbackId {
        StatusEffectUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StatusEffectUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `status_effect`,
/// which allows point queries on the field of the same name
/// via the [`StatusEffectIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.status_effect().id().find(...)`.
pub struct StatusEffectIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StatusEffectRow, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StatusEffectTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `status_effect`.
    pub fn id(&self) -> StatusEffectIdUnique<'ctx> {
        StatusEffectIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StatusEffectIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StatusEffectRow> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StatusEffectRow>("status_effect");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StatusEffectRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StatusEffectRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StatusEffectRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait status_effectQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StatusEffectRow`.
    fn status_effect(&self) -> __sdk::__query_builder::Table<StatusEffectRow>;
}

impl status_effectQueryTableAccess for __sdk::QueryTableAccessor {
    fn status_effect(&self) -> __sdk::__query_builder::Table<StatusEffectRow> {
        __sdk::__query_builder::Table::new("status_effect")
    }
}
