// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tick_stats_type::TickStats;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tick_stats`.
///
/// Obtain a handle from the [`TickStatsTableAccess::tick_stats`] method on [`super::RemoteTables`],
/// like `ctx.db.tick_stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tick_stats().on_insert(...)`.
pub struct TickStatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TickStats>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `tick_stats`.
pub struct TickStatsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TickStatsTableAccessor {
    type Row = TickStats;
    type Handle<'db> = TickStatsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.tick_stats()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tick_stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TickStatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TickStatsTableHandle`], which mediates access to the table `tick_stats`.
    fn tick_stats(&self) -> TickStatsTableHandle<'_>;
}

impl TickStatsTableAccess for super::RemoteTables {
    fn tick_stats(&self) -> TickStatsTableHandle<'_> {
        TickStatsTableHandle {
            imp: self.imp.get_table::<TickStats>("tick_stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TickStatsInsertCallbackId(__sdk::CallbackId);
pub struct TickStatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TickStatsTableHandle<'ctx> {
    type Row = TickStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TickStats> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TickStatsTableHandle<'ctx> {
    type Row = TickStats;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TickStats> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TickStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TickStatsInsertCallbackId {
        TickStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TickStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TickStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TickStatsDeleteCallbackId {
        TickStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TickStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TickStatsTableHandle<'ctx> {
    type InsertCallbackId = TickStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TickStatsInsertCallbackId {
        TickStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TickStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TickStatsTableHandle<'ctx> {
    type DeleteCallbackId = TickStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TickStatsDeleteCallbackId {
        TickStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TickStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TickStatsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TickStatsTableHandle<'ctx> {
    type UpdateCallbackId = TickStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TickStatsUpdateCallbackId {
        TickStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TickStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for TickStatsTableHandle<'ctx> {
    type UpdateCallbackId = TickStatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TickStatsUpdateCallbackId {
        TickStatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TickStatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `tick_stats`,
/// which allows point queries on the field of the same name
/// via the [`TickStatsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tick_stats().id().find(...)`.
pub struct TickStatsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TickStats, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TickStatsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `tick_stats`.
    pub fn id(&self) -> TickStatsIdUnique<'ctx> {
        TickStatsIdUnique {
            imp: self.imp.get_unique_constraint::<u8>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TickStatsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<TickStats> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TickStats>("tick_stats");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TickStats>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TickStats>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TickStats`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait tick_statsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TickStats`.
    fn tick_stats(&self) -> __sdk::__query_builder::Table<TickStats>;
}

impl tick_statsQueryTableAccess for __sdk::QueryTableAccessor {
    fn tick_stats(&self) -> __sdk::__query_builder::Table<TickStats> {
        __sdk::__query_builder::Table::new("tick_stats")
    }
}
