// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TickStats {
    pub id: u8,
    pub ticks: u64,
    pub last_tick_entities: u32,
    pub max_gap_us: i64,
    pub last_at_us: i64,
    pub next_recovery_at_us: i64,
}

impl __sdk::InModule for TickStats {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TickStats`.
///
/// Provides typed access to columns for query building.
pub struct TickStatsCols {
    pub id: __sdk::__query_builder::Col<TickStats, u8>,
    pub ticks: __sdk::__query_builder::Col<TickStats, u64>,
    pub last_tick_entities: __sdk::__query_builder::Col<TickStats, u32>,
    pub max_gap_us: __sdk::__query_builder::Col<TickStats, i64>,
    pub last_at_us: __sdk::__query_builder::Col<TickStats, i64>,
    pub next_recovery_at_us: __sdk::__query_builder::Col<TickStats, i64>,
}

impl __sdk::__query_builder::HasCols for TickStats {
    type Cols = TickStatsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TickStatsCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticks: __sdk::__query_builder::Col::new(table_name, "ticks"),
            last_tick_entities: __sdk::__query_builder::Col::new(table_name, "last_tick_entities"),
            max_gap_us: __sdk::__query_builder::Col::new(table_name, "max_gap_us"),
            last_at_us: __sdk::__query_builder::Col::new(table_name, "last_at_us"),
            next_recovery_at_us: __sdk::__query_builder::Col::new(
                table_name,
                "next_recovery_at_us",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `TickStats`.
///
/// Provides typed access to indexed columns for query building.
pub struct TickStatsIxCols {
    pub id: __sdk::__query_builder::IxCol<TickStats, u8>,
}

impl __sdk::__query_builder::HasIxCols for TickStats {
    type IxCols = TickStatsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TickStatsIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TickStats {}
