// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::trade_slot_type::TradeSlot;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TradeOfferArgs {
    pub slots: Vec<TradeSlot>,
    pub money: i64,
}

impl From<TradeOfferArgs> for super::Reducer {
    fn from(args: TradeOfferArgs) -> Self {
        Self::TradeOffer {
            slots: args.slots,
            money: args.money,
        }
    }
}

impl __sdk::InModule for TradeOfferArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `trade_offer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait trade_offer {
    /// Request that the remote module invoke the reducer `trade_offer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`trade_offer:trade_offer_then`] to run a callback after the reducer completes.
    fn trade_offer(&self, slots: Vec<TradeSlot>, money: i64) -> __sdk::Result<()> {
        self.trade_offer_then(slots, money, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `trade_offer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn trade_offer_then(
        &self,
        slots: Vec<TradeSlot>,
        money: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl trade_offer for super::RemoteReducers {
    fn trade_offer_then(
        &self,
        slots: Vec<TradeSlot>,
        money: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TradeOfferArgs { slots, money }, callback)
    }
}
