// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnequipVehiclePartArgs {
    pub part: u8,
}

impl From<UnequipVehiclePartArgs> for super::Reducer {
    fn from(args: UnequipVehiclePartArgs) -> Self {
        Self::UnequipVehiclePart { part: args.part }
    }
}

impl __sdk::InModule for UnequipVehiclePartArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unequip_vehicle_part`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unequip_vehicle_part {
    /// Request that the remote module invoke the reducer `unequip_vehicle_part` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`unequip_vehicle_part:unequip_vehicle_part_then`] to run a callback after the reducer completes.
    fn unequip_vehicle_part(&self, part: u8) -> __sdk::Result<()> {
        self.unequip_vehicle_part_then(part, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `unequip_vehicle_part` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unequip_vehicle_part_then(
        &self,
        part: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl unequip_vehicle_part for super::RemoteReducers {
    fn unequip_vehicle_part_then(
        &self,
        part: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UnequipVehiclePartArgs { part }, callback)
    }
}
